#define TT_PLUS                             1
#define TT_MINUS                            2
#define TT_SLASH                            3
#define TT_STAR                             4
#define TT_BANG                             5
#define TT_BANG_EQUAL                       6
#define TT_EQUAL_EQUAL                      7
#define TT_GREATER                          8
#define TT_GREATER_EQUAL                    9
#define TT_LESS                            10
#define TT_LESS_EQUAL                      11
#define TT_NOT                             12
#define TT_CARET                           13
#define TT_PERCENT                         14
#define TT_PIPE                            15
#define TT_AMPERSAND                       16
#define TT_SEMICOLON                       17
#define TT_COLON                           18
#define TT_LEFT_BRACKET                    19
#define TT_RIGHT_BRACKET                   20
#define TT_LEFT_BRACE                      21
#define TT_RIGHT_BRACE                     22
#define TT_LEFT_PAREN                      23
#define TT_RIGHT_PAREN                     24
#define TT_COMMA                           25
#define TT_STRING                          26
#define TT_IDENTIFIER                      27
#define TT_INTEGER                         28
#define TT_FLOAT                           29
#define TT_CREATE                          30
#define TT_DELETE                          31
#define TT_APPEND                          32
#define TT_INSERT                          33
#define TT_UPDATE                          34
#define TT_READ                            35
#define TT_TAKE                            36
#define TT_BCREATE                         37
#define TT_BDELETE                         38
#define TT_BAPPEND                         39
#define TT_BINSERT                         40
#define TT_BUPDATE                         41
#define TT_BREAD                           42
#define TT_BTAKE                           43
#define TT_STRUCT                          44
#define TT_UNION                           45
#define TT_ENUM                            46
#define TT_PRIM                            47
#define TT_TRUE                            48
#define TT_FALSE                           49
#define TT_IDENT                           50
