#define TT_CREATE                           1
#define TT_DELETE                           2
#define TT_APPEND                           3
#define TT_INSERT                           4
#define TT_UPDATE                           5
#define TT_READ                             6
#define TT_TAKE                             7
#define TT_BCREATE                          8
#define TT_BDELETE                          9
#define TT_BAPPEND                         10
#define TT_BINSERT                         11
#define TT_BUPDATE                         12
#define TT_BREAD                           13
#define TT_BTAKE                           14
#define TT_STRUCT                          15
#define TT_UNION                           16
#define TT_ENUM                            17
#define TT_PRIM                            18
#define TT_IDENTIFIER                      19
#define TT_STRING                          20
#define TT_INTEGER                         21
#define TT_FLOAT                           22
#define TT_SEMICOLON                       23
#define TT_LEFT_BRACKET                    24
#define TT_RIGHT_BRACKET                   25
#define TT_LEFT_BRACE                      26
#define TT_RIGHT_BRACE                     27
#define TT_LEFT_PAREN                      28
#define TT_RIGHT_PAREN                     29
#define TT_COMMA                           30
