/* This file is automatically generated by Lemon from input grammar
** source file "./tools/lemon/parser.y".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifier prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#include "compiler/parser.h"
#include "compiler/tokens.h"        

#include "numstore/type/builders/enum.h"
#include "numstore/type/builders/kvt.h"
#include "numstore/type/builders/sarray.h"

#include "numstore/query/builders/create.h"
#include "numstore/query/builders/delete.h"
#include "numstore/query/builders/insert.h"

#include "compiler/value/builders/object.h"
#include "compiler/value/builders/array.h"

#include "numstore/type/types.h"      

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wtype-limits"
#pragma GCC diagnostic ignored "-Wpedantic"
#line 52 "./tools/lemon/parser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef TT_PLUS
#define TT_PLUS                            1
#define TT_MINUS                           2
#define TT_SLASH                           3
#define TT_STAR                            4
#define TT_BANG                            5
#define TT_BANG_EQUAL                      6
#define TT_EQUAL_EQUAL                     7
#define TT_GREATER                         8
#define TT_GREATER_EQUAL                   9
#define TT_LESS                           10
#define TT_LESS_EQUAL                     11
#define TT_NOT                            12
#define TT_CARET                          13
#define TT_PERCENT                        14
#define TT_PIPE                           15
#define TT_AMPERSAND                      16
#define TT_SEMICOLON                      17
#define TT_COLON                          18
#define TT_LEFT_BRACKET                   19
#define TT_RIGHT_BRACKET                  20
#define TT_LEFT_BRACE                     21
#define TT_RIGHT_BRACE                    22
#define TT_LEFT_PAREN                     23
#define TT_RIGHT_PAREN                    24
#define TT_COMMA                          25
#define TT_STRING                         26
#define TT_IDENTIFIER                     27
#define TT_INTEGER                        28
#define TT_FLOAT                          29
#define TT_CREATE                         30
#define TT_DELETE                         31
#define TT_APPEND                         32
#define TT_INSERT                         33
#define TT_UPDATE                         34
#define TT_READ                           35
#define TT_TAKE                           36
#define TT_BCREATE                        37
#define TT_BDELETE                        38
#define TT_BAPPEND                        39
#define TT_BINSERT                        40
#define TT_BUPDATE                        41
#define TT_BREAD                          42
#define TT_BTAKE                          43
#define TT_STRUCT                         44
#define TT_UNION                          45
#define TT_ENUM                           46
#define TT_PRIM                           47
#define TT_TRUE                           48
#define TT_FALSE                          49
#define TT_IDENT                          50
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    lemon_parseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is lemon_parseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    lemon_parseARG_SDECL     A static variable declaration for the %extra_argument
**    lemon_parseARG_PDECL     A parameter declaration for the %extra_argument
**    lemon_parseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    lemon_parseARG_STORE     Code to store %extra_argument into yypParser
**    lemon_parseARG_FETCH     Code to extract %extra_argument from yypParser
**    lemon_parseCTX_*         As lemon_parseARG_ except for %extra_context
**    YYREALLOC          Name of the realloc() function to use
**    YYFREE             Name of the free() function to use
**    YYDYNSTACK         True if stack space should be extended on heap
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
**    YY_MIN_DSTRCTR     Minimum symbol value that has a destructor
**    YY_MAX_DSTRCTR     Maximum symbol value that has a destructor
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 74
#define YYACTIONTYPE unsigned char
#define lemon_parseTOKENTYPE token
typedef union {
  int yyinit;
  lemon_parseTOKENTYPE yy0;
  sarray_builder yy5;
  object_builder yy18;
  value yy54;
  array_builder yy58;
  type yy107;
  enum_builder yy112;
  query yy115;
  kvt_builder yy124;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define lemon_parseARG_SDECL  parser_result *res ;
#define lemon_parseARG_PDECL , parser_result *res 
#define lemon_parseARG_PARAM ,res 
#define lemon_parseARG_FETCH  parser_result *res =yypParser->res ;
#define lemon_parseARG_STORE yypParser->res =res ;
#define YYREALLOC realloc
#define YYFREE free
#define YYDYNSTACK 0
#define lemon_parseCTX_SDECL
#define lemon_parseCTX_PDECL
#define lemon_parseCTX_PARAM
#define lemon_parseCTX_FETCH
#define lemon_parseCTX_STORE
#define YYNSTATE             39
#define YYNRULE              43
#define YYNRULE_WITH_ACTION  40
#define YYNTOKEN             51
#define YY_MAX_SHIFT         38
#define YY_MIN_SHIFTREDUCE   79
#define YY_MAX_SHIFTREDUCE   121
#define YY_ERROR_ACTION      122
#define YY_ACCEPT_ACTION     123
#define YY_NO_ACTION         124
#define YY_MIN_REDUCE        125
#define YY_MAX_REDUCE        167
#define YY_MIN_DSTRCTR       0
#define YY_MAX_DSTRCTR       0
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif

/* Macro to determine if stack space has the ability to grow using
** heap memory.
*/
#if YYSTACKDEPTH<=0 || YYDYNSTACK
# define YYGROWABLESTACK 1
#else
# define YYGROWABLESTACK 0
#endif

/* Guarantee a minimum number of initial stack slots.
*/
#if YYSTACKDEPTH<=0
# undef YYSTACKDEPTH
# define YYSTACKDEPTH 2  /* Need a minimum stack size */
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (124)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   129,  148,  130,   19,  131,  155,  132,   21,  133,    6,
 /*    10 */   123,    8,   20,   22,  129,  151,  130,  124,  131,    7,
 /*    20 */   132,   13,  133,    6,  113,   14,   92,   25,   94,   95,
 /*    30 */   129,  152,  130,    2,  131,  116,  132,   23,  133,    6,
 /*    40 */    10,  135,  163,  136,  104,  137,   18,   31,   96,   97,
 /*    50 */    93,  129,  149,  130,    1,  131,   99,  132,   30,  133,
 /*    60 */     6,   30,  129,  156,  130,  165,  131,    9,  132,   12,
 /*    70 */   133,    6,  153,   11,  130,   24,  131,   26,  132,  111,
 /*    80 */   133,    6,   29,   34,   32,   36,   88,    3,  125,  127,
 /*    90 */   126,  128,   15,    4,  101,   37,   28,   33,   27,   16,
 /*   100 */   135,  160,  136,  100,  137,  135,  164,  136,   17,  137,
 /*   110 */    38,  135,  161,  136,  124,  137,  135,  158,  136,   98,
 /*   120 */   137,    5,   35,  121,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    55,   56,   57,   68,   59,   64,   61,   60,   63,   64,
 /*    10 */    71,   72,   62,   58,   55,   56,   57,   74,   59,   19,
 /*    20 */    61,   21,   63,   64,   22,   20,   26,   25,   28,   29,
 /*    30 */    55,   56,   57,   27,   59,   20,   61,   27,   63,   64,
 /*    40 */    25,   65,   66,   67,   22,   69,   70,   25,   48,   49,
 /*    50 */    50,   55,   56,   57,   27,   59,   27,   61,   19,   63,
 /*    60 */    64,   19,   55,   56,   57,    0,   59,   18,   61,   28,
 /*    70 */    63,   64,   55,   18,   57,   27,   59,   27,   61,   27,
 /*    80 */    63,   64,   28,   44,   45,   46,   47,   27,   51,   52,
 /*    90 */    53,   54,   21,   27,   22,   30,   31,   25,   33,   21,
 /*   100 */    65,   66,   67,   27,   69,   65,   66,   67,   21,   69,
 /*   110 */    73,   65,   66,   67,   74,   69,   65,   66,   67,   22,
 /*   120 */    69,   27,   25,   17,   74,   74,   74,   74,   74,   74,
 /*   130 */    74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
 /*   140 */    74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
 /*   150 */    74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
 /*   160 */    74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
 /*   170 */    74,   74,   74,   74,   74,
};
#define YY_SHIFT_COUNT    (38)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (106)
static const unsigned char yy_shift_ofst[] = {
 /*     0 */   124,   39,   39,   39,   39,   39,   39,    0,   65,    0,
 /*    10 */     0,    0,    0,   10,   42,    6,   27,   29,   15,    2,
 /*    20 */    22,   72,   97,   49,   55,   48,   41,   50,   52,    5,
 /*    30 */    54,   60,   71,   66,   78,   76,   87,   94,  106,
};
#define YY_REDUCE_COUNT (17)
#define YY_REDUCE_MIN   (-65)
#define YY_REDUCE_MAX   (51)
static const signed char yy_reduce_ofst[] = {
 /*     0 */   -61,  -55,  -41,  -25,   -4,    7,   17,  -24,   37,   35,
 /*    10 */    40,   46,   51,  -65,  -59,  -50,  -53,  -45,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   166,  122,  122,  122,  122,  122,  122,  122,  122,  122,
 /*    10 */   122,  122,  122,  122,  154,  122,  122,  122,  122,  122,
 /*    20 */   122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
 /*    30 */   122,  122,  122,  122,  122,  122,  122,  122,  122,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  lemon_parseARG_SDECL                /* A place to hold %extra_argument */
  lemon_parseCTX_SDECL                /* A place to hold %extra_context */
  yyStackEntry *yystackEnd;           /* Last entry in the stack */
  yyStackEntry *yystack;              /* The parser stack */
  yyStackEntry yystk0[YYSTACKDEPTH];  /* Initial stack space */
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void lemon_parseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "PLUS",
  /*    2 */ "MINUS",
  /*    3 */ "SLASH",
  /*    4 */ "STAR",
  /*    5 */ "BANG",
  /*    6 */ "BANG_EQUAL",
  /*    7 */ "EQUAL_EQUAL",
  /*    8 */ "GREATER",
  /*    9 */ "GREATER_EQUAL",
  /*   10 */ "LESS",
  /*   11 */ "LESS_EQUAL",
  /*   12 */ "NOT",
  /*   13 */ "CARET",
  /*   14 */ "PERCENT",
  /*   15 */ "PIPE",
  /*   16 */ "AMPERSAND",
  /*   17 */ "SEMICOLON",
  /*   18 */ "COLON",
  /*   19 */ "LEFT_BRACKET",
  /*   20 */ "RIGHT_BRACKET",
  /*   21 */ "LEFT_BRACE",
  /*   22 */ "RIGHT_BRACE",
  /*   23 */ "LEFT_PAREN",
  /*   24 */ "RIGHT_PAREN",
  /*   25 */ "COMMA",
  /*   26 */ "STRING",
  /*   27 */ "IDENTIFIER",
  /*   28 */ "INTEGER",
  /*   29 */ "FLOAT",
  /*   30 */ "CREATE",
  /*   31 */ "DELETE",
  /*   32 */ "APPEND",
  /*   33 */ "INSERT",
  /*   34 */ "UPDATE",
  /*   35 */ "READ",
  /*   36 */ "TAKE",
  /*   37 */ "BCREATE",
  /*   38 */ "BDELETE",
  /*   39 */ "BAPPEND",
  /*   40 */ "BINSERT",
  /*   41 */ "BUPDATE",
  /*   42 */ "BREAD",
  /*   43 */ "BTAKE",
  /*   44 */ "STRUCT",
  /*   45 */ "UNION",
  /*   46 */ "ENUM",
  /*   47 */ "PRIM",
  /*   48 */ "TRUE",
  /*   49 */ "FALSE",
  /*   50 */ "IDENT",
  /*   51 */ "query",
  /*   52 */ "create_decl",
  /*   53 */ "delete_decl",
  /*   54 */ "insert_decl",
  /*   55 */ "type",
  /*   56 */ "type_spec",
  /*   57 */ "enum_decl",
  /*   58 */ "enum_items",
  /*   59 */ "struct_decl",
  /*   60 */ "struct_items",
  /*   61 */ "union_decl",
  /*   62 */ "union_items",
  /*   63 */ "sarray_decl",
  /*   64 */ "sarray_dims",
  /*   65 */ "value",
  /*   66 */ "value_spec",
  /*   67 */ "object_decl",
  /*   68 */ "object_items",
  /*   69 */ "array_decl",
  /*   70 */ "array_items",
  /*   71 */ "main",
  /*   72 */ "in",
  /*   73 */ "state",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "state ::= query",
 /*   1 */ "query ::= delete_decl",
 /*   2 */ "query ::= create_decl",
 /*   3 */ "query ::= insert_decl",
 /*   4 */ "type_spec ::= type",
 /*   5 */ "type ::= enum_decl",
 /*   6 */ "type ::= struct_decl",
 /*   7 */ "type ::= union_decl",
 /*   8 */ "type ::= sarray_decl",
 /*   9 */ "type ::= PRIM",
 /*  10 */ "value_spec ::= value",
 /*  11 */ "value ::= object_decl",
 /*  12 */ "value ::= array_decl",
 /*  13 */ "value ::= STRING",
 /*  14 */ "value ::= IDENT",
 /*  15 */ "value ::= INTEGER",
 /*  16 */ "value ::= FLOAT",
 /*  17 */ "value ::= TRUE",
 /*  18 */ "value ::= FALSE",
 /*  19 */ "enum_decl ::= ENUM LEFT_BRACE enum_items RIGHT_BRACE",
 /*  20 */ "enum_items ::= IDENTIFIER",
 /*  21 */ "enum_items ::= enum_items COMMA IDENTIFIER",
 /*  22 */ "struct_decl ::= STRUCT LEFT_BRACE struct_items RIGHT_BRACE",
 /*  23 */ "struct_items ::= IDENTIFIER type_spec",
 /*  24 */ "struct_items ::= struct_items COMMA IDENTIFIER type_spec",
 /*  25 */ "union_decl ::= UNION LEFT_BRACE union_items RIGHT_BRACE",
 /*  26 */ "union_items ::= IDENTIFIER type_spec",
 /*  27 */ "union_items ::= union_items COMMA IDENTIFIER type_spec",
 /*  28 */ "sarray_decl ::= sarray_dims type",
 /*  29 */ "sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET",
 /*  30 */ "sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET sarray_dims",
 /*  31 */ "create_decl ::= CREATE IDENTIFIER type_spec",
 /*  32 */ "delete_decl ::= DELETE IDENTIFIER",
 /*  33 */ "insert_decl ::= INSERT IDENTIFIER INTEGER value_spec",
 /*  34 */ "object_decl ::= LEFT_BRACE object_items RIGHT_BRACE",
 /*  35 */ "object_items ::= IDENTIFIER COLON value_spec",
 /*  36 */ "object_items ::= object_items COMMA IDENTIFIER COLON value_spec",
 /*  37 */ "array_decl ::= LEFT_BRACKET array_items RIGHT_BRACKET",
 /*  38 */ "array_items ::= value_spec",
 /*  39 */ "array_items ::= array_items COMMA value_spec",
 /*  40 */ "main ::= in",
 /*  41 */ "in ::=",
 /*  42 */ "in ::= in state SEMICOLON",
};
#endif /* NDEBUG */


#if YYGROWABLESTACK
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int oldSize = 1 + (int)(p->yystackEnd - p->yystack);
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = oldSize*2 + 100;
  idx = (int)(p->yytos - p->yystack);
  if( p->yystack==p->yystk0 ){
    pNew = YYREALLOC(0, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
    memcpy(pNew, p->yystack, oldSize*sizeof(pNew[0]));
  }else{
    pNew = YYREALLOC(p->yystack, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
  }
  p->yystack = pNew;
  p->yytos = &p->yystack[idx];
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
            yyTracePrompt, oldSize, newSize);
  }
#endif
  p->yystackEnd = &p->yystack[newSize-1];
  return 0;
}
#endif /* YYGROWABLESTACK */

#if !YYGROWABLESTACK
/* For builds that do no have a growable stack, yyGrowStack always
** returns an error.
*/
# define yyGrowStack(X) 1
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to lemon_parseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void lemon_parseInit(void *yypRawParser lemon_parseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  lemon_parseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
  yypParser->yystack = yypParser->yystk0;
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
}

#ifndef lemon_parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to lemon_parse and lemon_parseFree.
*/
void *lemon_parseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) lemon_parseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    lemon_parseCTX_STORE
    lemon_parseInit(yypParser lemon_parseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* lemon_parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  lemon_parseARG_FETCH
  lemon_parseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void lemon_parseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;

  /* In-lined version of calling yy_pop_parser_stack() for each
  ** element left in the stack */
  yyStackEntry *yytos = pParser->yytos;
  while( yytos>pParser->yystack ){
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sPopping %s\n",
        yyTracePrompt,
        yyTokenName[yytos->major]);
    }
#endif
    if( yytos->major>=YY_MIN_DSTRCTR ){
      yy_destructor(pParser, yytos->major, &yytos->minor);
    }
    yytos--;
  }

#if YYGROWABLESTACK
  if( pParser->yystack!=pParser->yystk0 ) YYFREE(pParser->yystack);
#endif
}

#ifndef lemon_parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void lemon_parseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  lemon_parseFinalize(p);
  (*freeProc)(p);
}
#endif /* lemon_parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int lemon_parseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int lemon_parseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   lemon_parseARG_FETCH
   lemon_parseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   lemon_parseARG_STORE /* Suppress warning about unused %extra_argument var */
   lemon_parseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  lemon_parseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
  yytos = yypParser->yytos;
  if( yytos>yypParser->yystackEnd ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
    yytos = yypParser->yytos;
    assert( yytos <= yypParser->yystackEnd );
  }
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    73,  /* (0) state ::= query */
    51,  /* (1) query ::= delete_decl */
    51,  /* (2) query ::= create_decl */
    51,  /* (3) query ::= insert_decl */
    56,  /* (4) type_spec ::= type */
    55,  /* (5) type ::= enum_decl */
    55,  /* (6) type ::= struct_decl */
    55,  /* (7) type ::= union_decl */
    55,  /* (8) type ::= sarray_decl */
    55,  /* (9) type ::= PRIM */
    66,  /* (10) value_spec ::= value */
    65,  /* (11) value ::= object_decl */
    65,  /* (12) value ::= array_decl */
    65,  /* (13) value ::= STRING */
    65,  /* (14) value ::= IDENT */
    65,  /* (15) value ::= INTEGER */
    65,  /* (16) value ::= FLOAT */
    65,  /* (17) value ::= TRUE */
    65,  /* (18) value ::= FALSE */
    57,  /* (19) enum_decl ::= ENUM LEFT_BRACE enum_items RIGHT_BRACE */
    58,  /* (20) enum_items ::= IDENTIFIER */
    58,  /* (21) enum_items ::= enum_items COMMA IDENTIFIER */
    59,  /* (22) struct_decl ::= STRUCT LEFT_BRACE struct_items RIGHT_BRACE */
    60,  /* (23) struct_items ::= IDENTIFIER type_spec */
    60,  /* (24) struct_items ::= struct_items COMMA IDENTIFIER type_spec */
    61,  /* (25) union_decl ::= UNION LEFT_BRACE union_items RIGHT_BRACE */
    62,  /* (26) union_items ::= IDENTIFIER type_spec */
    62,  /* (27) union_items ::= union_items COMMA IDENTIFIER type_spec */
    63,  /* (28) sarray_decl ::= sarray_dims type */
    64,  /* (29) sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET */
    64,  /* (30) sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET sarray_dims */
    52,  /* (31) create_decl ::= CREATE IDENTIFIER type_spec */
    53,  /* (32) delete_decl ::= DELETE IDENTIFIER */
    54,  /* (33) insert_decl ::= INSERT IDENTIFIER INTEGER value_spec */
    67,  /* (34) object_decl ::= LEFT_BRACE object_items RIGHT_BRACE */
    68,  /* (35) object_items ::= IDENTIFIER COLON value_spec */
    68,  /* (36) object_items ::= object_items COMMA IDENTIFIER COLON value_spec */
    69,  /* (37) array_decl ::= LEFT_BRACKET array_items RIGHT_BRACKET */
    70,  /* (38) array_items ::= value_spec */
    70,  /* (39) array_items ::= array_items COMMA value_spec */
    71,  /* (40) main ::= in */
    72,  /* (41) in ::= */
    72,  /* (42) in ::= in state SEMICOLON */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) state ::= query */
   -1,  /* (1) query ::= delete_decl */
   -1,  /* (2) query ::= create_decl */
   -1,  /* (3) query ::= insert_decl */
   -1,  /* (4) type_spec ::= type */
   -1,  /* (5) type ::= enum_decl */
   -1,  /* (6) type ::= struct_decl */
   -1,  /* (7) type ::= union_decl */
   -1,  /* (8) type ::= sarray_decl */
   -1,  /* (9) type ::= PRIM */
   -1,  /* (10) value_spec ::= value */
   -1,  /* (11) value ::= object_decl */
   -1,  /* (12) value ::= array_decl */
   -1,  /* (13) value ::= STRING */
   -1,  /* (14) value ::= IDENT */
   -1,  /* (15) value ::= INTEGER */
   -1,  /* (16) value ::= FLOAT */
   -1,  /* (17) value ::= TRUE */
   -1,  /* (18) value ::= FALSE */
   -4,  /* (19) enum_decl ::= ENUM LEFT_BRACE enum_items RIGHT_BRACE */
   -1,  /* (20) enum_items ::= IDENTIFIER */
   -3,  /* (21) enum_items ::= enum_items COMMA IDENTIFIER */
   -4,  /* (22) struct_decl ::= STRUCT LEFT_BRACE struct_items RIGHT_BRACE */
   -2,  /* (23) struct_items ::= IDENTIFIER type_spec */
   -4,  /* (24) struct_items ::= struct_items COMMA IDENTIFIER type_spec */
   -4,  /* (25) union_decl ::= UNION LEFT_BRACE union_items RIGHT_BRACE */
   -2,  /* (26) union_items ::= IDENTIFIER type_spec */
   -4,  /* (27) union_items ::= union_items COMMA IDENTIFIER type_spec */
   -2,  /* (28) sarray_decl ::= sarray_dims type */
   -3,  /* (29) sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET */
   -4,  /* (30) sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET sarray_dims */
   -3,  /* (31) create_decl ::= CREATE IDENTIFIER type_spec */
   -2,  /* (32) delete_decl ::= DELETE IDENTIFIER */
   -4,  /* (33) insert_decl ::= INSERT IDENTIFIER INTEGER value_spec */
   -3,  /* (34) object_decl ::= LEFT_BRACE object_items RIGHT_BRACE */
   -3,  /* (35) object_items ::= IDENTIFIER COLON value_spec */
   -5,  /* (36) object_items ::= object_items COMMA IDENTIFIER COLON value_spec */
   -3,  /* (37) array_decl ::= LEFT_BRACKET array_items RIGHT_BRACKET */
   -1,  /* (38) array_items ::= value_spec */
   -3,  /* (39) array_items ::= array_items COMMA value_spec */
   -1,  /* (40) main ::= in */
    0,  /* (41) in ::= */
   -3,  /* (42) in ::= in state SEMICOLON */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  lemon_parseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  lemon_parseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  lemon_parseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* state ::= query */
#line 124 "./tools/lemon/parser.y"
{
    res->result = yymsp[0].minor.yy115;
    res->ready = true;
}
#line 1138 "./tools/lemon/parser.c"
        break;
      case 1: /* query ::= delete_decl */
      case 2: /* query ::= create_decl */ yytestcase(yyruleno==2);
      case 3: /* query ::= insert_decl */ yytestcase(yyruleno==3);
#line 130 "./tools/lemon/parser.y"
{
    yylhsminor.yy115 = yymsp[0].minor.yy115;
}
#line 1147 "./tools/lemon/parser.c"
  yymsp[0].minor.yy115 = yylhsminor.yy115;
        break;
      case 4: /* type_spec ::= type */
#line 143 "./tools/lemon/parser.y"
{ yylhsminor.yy107 = yymsp[0].minor.yy107; }
#line 1153 "./tools/lemon/parser.c"
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 5: /* type ::= enum_decl */
#line 145 "./tools/lemon/parser.y"
{
    yylhsminor.yy107 = (type){ .type = T_ENUM };
    if (enb_build(&yylhsminor.yy107.en, &yymsp[0].minor.yy112, res->e) != 0) break;
}
#line 1162 "./tools/lemon/parser.c"
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 6: /* type ::= struct_decl */
#line 150 "./tools/lemon/parser.y"
{
    yylhsminor.yy107 = (type){ .type = T_STRUCT };
    if (kvb_struct_t_build(&yylhsminor.yy107.st, &yymsp[0].minor.yy124, res->e) != 0) break;
}
#line 1171 "./tools/lemon/parser.c"
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 7: /* type ::= union_decl */
#line 155 "./tools/lemon/parser.y"
{
    yylhsminor.yy107 = (type){ .type = T_UNION };
    if (kvb_union_t_build(&yylhsminor.yy107.un, &yymsp[0].minor.yy124, res->e) != 0) break;
}
#line 1180 "./tools/lemon/parser.c"
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 8: /* type ::= sarray_decl */
#line 160 "./tools/lemon/parser.y"
{
    yylhsminor.yy107 = (type){ .type = T_SARRAY };
    if (sab_build(&yylhsminor.yy107.sa, &yymsp[0].minor.yy5, res->e) != 0) break;
}
#line 1189 "./tools/lemon/parser.c"
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 9: /* type ::= PRIM */
#line 165 "./tools/lemon/parser.y"
{
  yylhsminor.yy107 = (type){ 
    .type = T_PRIM,
    .p = yymsp[0].minor.yy0.prim,
  };
}
#line 1200 "./tools/lemon/parser.c"
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 10: /* value_spec ::= value */
#line 173 "./tools/lemon/parser.y"
{ yylhsminor.yy54 = yymsp[0].minor.yy54; }
#line 1206 "./tools/lemon/parser.c"
  yymsp[0].minor.yy54 = yylhsminor.yy54;
        break;
      case 11: /* value ::= object_decl */
#line 175 "./tools/lemon/parser.y"
{
  yylhsminor.yy54 = (value){ .type = VT_OBJECT };
  if(objb_build(&yylhsminor.yy54.obj, &yymsp[0].minor.yy18, res->e) != 0) break;
}
#line 1215 "./tools/lemon/parser.c"
  yymsp[0].minor.yy54 = yylhsminor.yy54;
        break;
      case 12: /* value ::= array_decl */
#line 180 "./tools/lemon/parser.y"
{
  yylhsminor.yy54 = (value){ .type = VT_ARRAY };
  if(arb_build(&yylhsminor.yy54.arr, &yymsp[0].minor.yy58, res->e) != 0) break;
}
#line 1224 "./tools/lemon/parser.c"
  yymsp[0].minor.yy54 = yylhsminor.yy54;
        break;
      case 13: /* value ::= STRING */
#line 186 "./tools/lemon/parser.y"
{
  yylhsminor.yy54 = value_string_create(yymsp[0].minor.yy0.str); 
}
#line 1232 "./tools/lemon/parser.c"
  yymsp[0].minor.yy54 = yylhsminor.yy54;
        break;
      case 14: /* value ::= IDENT */
#line 190 "./tools/lemon/parser.y"
{
  yylhsminor.yy54 = value_ident_create(yymsp[0].minor.yy0.str); 
}
#line 1240 "./tools/lemon/parser.c"
  yymsp[0].minor.yy54 = yylhsminor.yy54;
        break;
      case 15: /* value ::= INTEGER */
#line 194 "./tools/lemon/parser.y"
{
  yylhsminor.yy54 = value_number_create(yymsp[0].minor.yy0.integer); 
}
#line 1248 "./tools/lemon/parser.c"
  yymsp[0].minor.yy54 = yylhsminor.yy54;
        break;
      case 16: /* value ::= FLOAT */
#line 198 "./tools/lemon/parser.y"
{
  yylhsminor.yy54 = value_number_create(yymsp[0].minor.yy0.floating); 
}
#line 1256 "./tools/lemon/parser.c"
  yymsp[0].minor.yy54 = yylhsminor.yy54;
        break;
      case 17: /* value ::= TRUE */
#line 204 "./tools/lemon/parser.y"
{
  yymsp[0].minor.yy54 = value_true_create(); 
}
#line 1264 "./tools/lemon/parser.c"
        break;
      case 18: /* value ::= FALSE */
#line 208 "./tools/lemon/parser.y"
{
  yymsp[0].minor.yy54 = value_false_create(); 
}
#line 1271 "./tools/lemon/parser.c"
        break;
      case 19: /* enum_decl ::= ENUM LEFT_BRACE enum_items RIGHT_BRACE */
#line 215 "./tools/lemon/parser.y"
{ yymsp[-3].minor.yy112 = yymsp[-1].minor.yy112; }
#line 1276 "./tools/lemon/parser.c"
        break;
      case 20: /* enum_items ::= IDENTIFIER */
#line 218 "./tools/lemon/parser.y"
{
    yylhsminor.yy112 = enb_create(res->work, res->dest);
    if (enb_accept_key(&yylhsminor.yy112, yymsp[0].minor.yy0.str, res->e) != 0) break;
}
#line 1284 "./tools/lemon/parser.c"
  yymsp[0].minor.yy112 = yylhsminor.yy112;
        break;
      case 21: /* enum_items ::= enum_items COMMA IDENTIFIER */
#line 224 "./tools/lemon/parser.y"
{
    yylhsminor.yy112 = yymsp[-2].minor.yy112;
    if (enb_accept_key(&yylhsminor.yy112, yymsp[0].minor.yy0.str, res->e) != 0) break;
}
#line 1293 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy112 = yylhsminor.yy112;
        break;
      case 22: /* struct_decl ::= STRUCT LEFT_BRACE struct_items RIGHT_BRACE */
      case 25: /* union_decl ::= UNION LEFT_BRACE union_items RIGHT_BRACE */ yytestcase(yyruleno==25);
#line 232 "./tools/lemon/parser.y"
{ yymsp[-3].minor.yy124 = yymsp[-1].minor.yy124; }
#line 1300 "./tools/lemon/parser.c"
        break;
      case 23: /* struct_items ::= IDENTIFIER type_spec */
#line 236 "./tools/lemon/parser.y"
{
    yylhsminor.yy124 = kvb_create(res->work, res->dest);                 /* <-- was “yylhsminor.yy124 = B;” (undefined) */
    if (kvb_accept_key (&yylhsminor.yy124, yymsp[-1].minor.yy0.str, res->e) != 0) break;
    if (kvb_accept_type(&yylhsminor.yy124, yymsp[0].minor.yy107,       res->e) != 0) break;
}
#line 1309 "./tools/lemon/parser.c"
  yymsp[-1].minor.yy124 = yylhsminor.yy124;
        break;
      case 24: /* struct_items ::= struct_items COMMA IDENTIFIER type_spec */
      case 27: /* union_items ::= union_items COMMA IDENTIFIER type_spec */ yytestcase(yyruleno==27);
#line 244 "./tools/lemon/parser.y"
{
    yylhsminor.yy124 = yymsp[-3].minor.yy124;
    if (kvb_accept_key (&yylhsminor.yy124, yymsp[-1].minor.yy0.str, res->e) != 0) break;
    if (kvb_accept_type(&yylhsminor.yy124, yymsp[0].minor.yy107,       res->e) != 0) break;
}
#line 1320 "./tools/lemon/parser.c"
  yymsp[-3].minor.yy124 = yylhsminor.yy124;
        break;
      case 26: /* union_items ::= IDENTIFIER type_spec */
#line 257 "./tools/lemon/parser.y"
{
    yylhsminor.yy124 = kvb_create(res->work, res->dest);
    if (kvb_accept_key (&yylhsminor.yy124, yymsp[-1].minor.yy0.str, res->e) != 0) break;
    if (kvb_accept_type(&yylhsminor.yy124, yymsp[0].minor.yy107,       res->e) != 0) break;
}
#line 1330 "./tools/lemon/parser.c"
  yymsp[-1].minor.yy124 = yylhsminor.yy124;
        break;
      case 28: /* sarray_decl ::= sarray_dims type */
#line 277 "./tools/lemon/parser.y"
{  
  if (sab_accept_type(&yymsp[-1].minor.yy5, yymsp[0].minor.yy107, res->e) != 0) break;
  yylhsminor.yy5 = yymsp[-1].minor.yy5; 
}
#line 1339 "./tools/lemon/parser.c"
  yymsp[-1].minor.yy5 = yylhsminor.yy5;
        break;
      case 29: /* sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET */
#line 283 "./tools/lemon/parser.y"
{ 
  yymsp[-2].minor.yy5 = sab_create(res->work, res->dest);
  if (sab_accept_dim(&yymsp[-2].minor.yy5, yymsp[-1].minor.yy0.integer, res->e) != 0) break;
}
#line 1348 "./tools/lemon/parser.c"
        break;
      case 30: /* sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET sarray_dims */
#line 289 "./tools/lemon/parser.y"
{
  if (sab_accept_dim(&yymsp[0].minor.yy5, yymsp[-2].minor.yy0.integer, res->e) != 0) break;
  yymsp[-3].minor.yy5 = yymsp[0].minor.yy5;
}
#line 1356 "./tools/lemon/parser.c"
        break;
      case 31: /* create_decl ::= CREATE IDENTIFIER type_spec */
#line 297 "./tools/lemon/parser.y"
{
    yylhsminor.yy115 = yymsp[-2].minor.yy0.q;

    // Build the builder
    create_builder tmp = crb_create();

    // Accept
    if (crb_accept_string(&tmp, yymsp[-1].minor.yy0.str, res->e) != 0) break;
    if (crb_accept_type(&tmp, yymsp[0].minor.yy107, res->e) != 0) break;

    // Build the query
    if (crb_build(yylhsminor.yy115.create, &tmp, res->e) != 0) break; 
}
#line 1373 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy115 = yylhsminor.yy115;
        break;
      case 32: /* delete_decl ::= DELETE IDENTIFIER */
#line 314 "./tools/lemon/parser.y"
{
    yylhsminor.yy115 = yymsp[-1].minor.yy0.q;

    // Build the builder
    delete_builder tmp = dltb_create();

    // Accept
    if (dltb_accept_string(&tmp, yymsp[0].minor.yy0.str, res->e) != 0) break;

    // Build the query
    if (dltb_build(yylhsminor.yy115.delete, &tmp, res->e) != 0) break; 
}
#line 1390 "./tools/lemon/parser.c"
  yymsp[-1].minor.yy115 = yylhsminor.yy115;
        break;
      case 33: /* insert_decl ::= INSERT IDENTIFIER INTEGER value_spec */
#line 330 "./tools/lemon/parser.y"
{
    yylhsminor.yy115 = yymsp[-3].minor.yy0.q;

    // Build the builder
    insert_builder tmp = inb_create();

    // Accept
    if (inb_accept_string(&tmp, yymsp[-2].minor.yy0.str, res->e) != 0) break;
    if (inb_accept_value(&tmp, yymsp[0].minor.yy54, res->e) != 0) break;
    if (inb_accept_start(&tmp, yymsp[-1].minor.yy0.integer, res->e) != 0) break;

    // Build the query
    if (inb_build(yylhsminor.yy115.insert, &tmp, res->e) != 0) break; 
}
#line 1409 "./tools/lemon/parser.c"
  yymsp[-3].minor.yy115 = yylhsminor.yy115;
        break;
      case 34: /* object_decl ::= LEFT_BRACE object_items RIGHT_BRACE */
#line 348 "./tools/lemon/parser.y"
{ yymsp[-2].minor.yy18 = yymsp[-1].minor.yy18; }
#line 1415 "./tools/lemon/parser.c"
        break;
      case 35: /* object_items ::= IDENTIFIER COLON value_spec */
#line 352 "./tools/lemon/parser.y"
{
    yylhsminor.yy18 = objb_create(res->work, res->dest);
    if (objb_accept_string(&yylhsminor.yy18, yymsp[-2].minor.yy0.str, res->e) != 0) break;
    if (objb_accept_value(&yylhsminor.yy18, yymsp[0].minor.yy54,       res->e) != 0) break;
}
#line 1424 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy18 = yylhsminor.yy18;
        break;
      case 36: /* object_items ::= object_items COMMA IDENTIFIER COLON value_spec */
#line 360 "./tools/lemon/parser.y"
{
    yylhsminor.yy18 = yymsp[-4].minor.yy18;
    if (objb_accept_string(&yylhsminor.yy18, yymsp[-2].minor.yy0.str, res->e) != 0) break;
    if (objb_accept_value(&yylhsminor.yy18, yymsp[0].minor.yy54,       res->e) != 0) break;
}
#line 1434 "./tools/lemon/parser.c"
  yymsp[-4].minor.yy18 = yylhsminor.yy18;
        break;
      case 37: /* array_decl ::= LEFT_BRACKET array_items RIGHT_BRACKET */
#line 369 "./tools/lemon/parser.y"
{  yymsp[-2].minor.yy58 = yymsp[-1].minor.yy58; }
#line 1440 "./tools/lemon/parser.c"
        break;
      case 38: /* array_items ::= value_spec */
#line 373 "./tools/lemon/parser.y"
{ 
  yylhsminor.yy58 = arb_create(res->work, res->dest);
  if (arb_accept_value(&yylhsminor.yy58, yymsp[0].minor.yy54, res->e) != 0) break;
}
#line 1448 "./tools/lemon/parser.c"
  yymsp[0].minor.yy58 = yylhsminor.yy58;
        break;
      case 39: /* array_items ::= array_items COMMA value_spec */
#line 380 "./tools/lemon/parser.y"
{
  yylhsminor.yy58 = yymsp[-2].minor.yy58;
  if (arb_accept_value(&yylhsminor.yy58, yymsp[0].minor.yy54, res->e) != 0) break;
}
#line 1457 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy58 = yylhsminor.yy58;
        break;
      default:
      /* (40) main ::= in */ yytestcase(yyruleno==40);
      /* (41) in ::= */ yytestcase(yyruleno==41);
      /* (42) in ::= in state SEMICOLON */ yytestcase(yyruleno==42);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  lemon_parseARG_FETCH
  lemon_parseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 111 "./tools/lemon/parser.y"

  error_causef(
    res->e, 
    ERR_SYNTAX, 
    "Parser error at index: %d\n", res->tnum);
#line 1511 "./tools/lemon/parser.c"
/************ End %parse_failure code *****************************************/
  lemon_parseARG_STORE /* Suppress warning about unused %extra_argument variable */
  lemon_parseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  lemon_parseTOKENTYPE yyminor         /* The minor type of the error token */
){
  lemon_parseARG_FETCH
  lemon_parseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 103 "./tools/lemon/parser.y"

  error_causef(
    res->e, 
    ERR_SYNTAX, 
    "Syntax error at token: %s at index: %d", 
    tt_tostr(yyminor.type), res->tnum);
#line 1537 "./tools/lemon/parser.c"
/************ End %syntax_error code ******************************************/
  lemon_parseARG_STORE /* Suppress warning about unused %extra_argument variable */
  lemon_parseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  lemon_parseARG_FETCH
  lemon_parseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  lemon_parseARG_STORE /* Suppress warning about unused %extra_argument variable */
  lemon_parseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "lemon_parseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void lemon_parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  lemon_parseTOKENTYPE yyminor       /* The value for the token */
  lemon_parseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  lemon_parseCTX_FETCH
  lemon_parseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
        if( yypParser->yytos>=yypParser->yystackEnd ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor lemon_parseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int lemon_parseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
