#define TT_PLUS                             1
#define TT_MINUS                            2
#define TT_SLASH                            3
#define TT_STAR                             4
#define TT_BANG                             5
#define TT_BANG_EQUAL                       6
#define TT_EQUAL_EQUAL                      7
#define TT_GREATER                          8
#define TT_GREATER_EQUAL                    9
#define TT_LESS                            10
#define TT_LESS_EQUAL                      11
#define TT_NOT                             12
#define TT_CARET                           13
#define TT_PERCENT                         14
#define TT_PIPE                            15
#define TT_AMPERSAND                       16
#define TT_SEMICOLON                       17
#define TT_COLON                           18
#define TT_LEFT_BRACKET                    19
#define TT_RIGHT_BRACKET                   20
#define TT_LEFT_BRACE                      21
#define TT_RIGHT_BRACE                     22
#define TT_LEFT_PAREN                      23
#define TT_RIGHT_PAREN                     24
#define TT_COMMA                           25
#define TT_STRING                          26
#define TT_IDENTIFIER                      27
#define TT_INTEGER                         28
#define TT_FLOAT                           29
#define TT_CREATE                          30
#define TT_DELETE                          31
#define TT_INSERT                          32
#define TT_STRUCT                          33
#define TT_UNION                           34
#define TT_ENUM                            35
#define TT_PRIM                            36
#define TT_TRUE                            37
#define TT_FALSE                           38
