/* This file is automatically generated by Lemon from input grammar
** source file "./tools/lemon/parser.y".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifier prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#include "compiler/parser.h"
#include "compiler/tokens.h"        

#include "numstore/type/builders/enum.h"
#include "numstore/type/builders/kvt.h"
#include "numstore/type/builders/sarray.h"

#include "numstore/query/builders/create.h"
#include "numstore/query/builders/delete.h"
#include "numstore/query/builders/insert.h"

#include "compiler/value/builders/object.h"
#include "compiler/value/builders/array.h"

#include "numstore/type/types.h"      
#include "compiler/expression.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wtype-limits"
#pragma GCC diagnostic ignored "-Wpedantic"
#line 53 "./tools/lemon/parser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef TT_PLUS
#define TT_PLUS                            1
#define TT_MINUS                           2
#define TT_SLASH                           3
#define TT_STAR                            4
#define TT_BANG                            5
#define TT_BANG_EQUAL                      6
#define TT_EQUAL_EQUAL                     7
#define TT_GREATER                         8
#define TT_GREATER_EQUAL                   9
#define TT_LESS                           10
#define TT_LESS_EQUAL                     11
#define TT_NOT                            12
#define TT_CARET                          13
#define TT_PERCENT                        14
#define TT_PIPE                           15
#define TT_AMPERSAND                      16
#define TT_SEMICOLON                      17
#define TT_COLON                          18
#define TT_LEFT_BRACKET                   19
#define TT_RIGHT_BRACKET                  20
#define TT_LEFT_BRACE                     21
#define TT_RIGHT_BRACE                    22
#define TT_LEFT_PAREN                     23
#define TT_RIGHT_PAREN                    24
#define TT_COMMA                          25
#define TT_STRING                         26
#define TT_IDENTIFIER                     27
#define TT_INTEGER                        28
#define TT_FLOAT                          29
#define TT_CREATE                         30
#define TT_DELETE                         31
#define TT_INSERT                         32
#define TT_STRUCT                         33
#define TT_UNION                          34
#define TT_ENUM                           35
#define TT_PRIM                           36
#define TT_TRUE                           37
#define TT_FALSE                          38
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    lemon_parseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is lemon_parseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    lemon_parseARG_SDECL     A static variable declaration for the %extra_argument
**    lemon_parseARG_PDECL     A parameter declaration for the %extra_argument
**    lemon_parseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    lemon_parseARG_STORE     Code to store %extra_argument into yypParser
**    lemon_parseARG_FETCH     Code to extract %extra_argument from yypParser
**    lemon_parseCTX_*         As lemon_parseARG_ except for %extra_context
**    YYREALLOC          Name of the realloc() function to use
**    YYFREE             Name of the free() function to use
**    YYDYNSTACK         True if stack space should be extended on heap
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
**    YY_MIN_DSTRCTR     Minimum symbol value that has a destructor
**    YY_MAX_DSTRCTR     Maximum symbol value that has a destructor
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 68
#define YYACTIONTYPE unsigned char
#define lemon_parseTOKENTYPE token
typedef union {
  int yyinit;
  lemon_parseTOKENTYPE yy0;
  kvt_builder yy8;
  array_builder yy22;
  expr* yy82;
  object_builder yy114;
  query yy115;
  sarray_builder yy117;
  type yy123;
  enum_builder yy128;
  value yy134;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define lemon_parseARG_SDECL  parser_result *res ;
#define lemon_parseARG_PDECL , parser_result *res 
#define lemon_parseARG_PARAM ,res 
#define lemon_parseARG_FETCH  parser_result *res =yypParser->res ;
#define lemon_parseARG_STORE yypParser->res =res ;
#define YYREALLOC realloc
#define YYFREE free
#define YYDYNSTACK 0
#define lemon_parseCTX_SDECL
#define lemon_parseCTX_PDECL
#define lemon_parseCTX_PARAM
#define lemon_parseCTX_FETCH
#define lemon_parseCTX_STORE
#define YYNSTATE             65
#define YYNRULE              61
#define YYNRULE_WITH_ACTION  58
#define YYNTOKEN             39
#define YY_MAX_SHIFT         64
#define YY_MIN_SHIFTREDUCE   111
#define YY_MAX_SHIFTREDUCE   171
#define YY_ERROR_ACTION      172
#define YY_ACCEPT_ACTION     173
#define YY_NO_ACTION         174
#define YY_MIN_REDUCE        175
#define YY_MAX_REDUCE        235
#define YY_MIN_DSTRCTR       0
#define YY_MAX_DSTRCTR       0
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif

/* Macro to determine if stack space has the ability to grow using
** heap memory.
*/
#if YYSTACKDEPTH<=0 || YYDYNSTACK
# define YYGROWABLESTACK 1
#else
# define YYGROWABLESTACK 0
#endif

/* Guarantee a minimum number of initial stack slots.
*/
#if YYSTACKDEPTH<=0
# undef YYSTACKDEPTH
# define YYSTACKDEPTH 2  /* Need a minimum stack size */
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (271)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   231,  185,  203,  186,   43,  211,   42,   32,   34,   37,
 /*    10 */   225,  230,   22,  231,  185,   23,  186,   44,  208,   42,
 /*    20 */    32,   34,   37,  225,  230,  175,  177,  176,  178,    1,
 /*    30 */    56,   26,   48,    3,  231,  185,  123,  186,  124,  125,
 /*    40 */    14,   31,   34,   37,  225,  230,  146,  126,  127,  231,
 /*    50 */   185,    4,  186,   64,   49,   42,   32,   34,   37,  225,
 /*    60 */   230,  231,  185,   47,  186,   45,  212,   42,   32,   34,
 /*    70 */    37,  225,  230,  231,  185,   13,  186,   46,  209,   42,
 /*    80 */    32,   34,   37,  225,  230,  231,  185,    2,  186,  129,
 /*    90 */   206,   42,   32,   34,   37,  225,  230,  231,  185,  168,
 /*   100 */   186,  173,   25,    5,   33,   34,   37,  225,  230,  231,
 /*   110 */   185,  233,  186,  231,  185,   56,  186,   35,   37,  225,
 /*   120 */   230,   36,   37,  225,  230,  231,  185,   50,  186,   60,
 /*   130 */    58,   62,  120,   39,   37,  225,  230,  231,  185,   52,
 /*   140 */   186,   63,   54,   53,    6,   41,   37,  225,  230,  179,
 /*   150 */   196,  180,  141,  181,   55,  182,  143,  183,   20,   51,
 /*   160 */   179,  199,  180,   27,  181,   15,  182,   28,  183,   20,
 /*   170 */   179,  200,  180,  174,  181,   29,  182,   16,  183,   20,
 /*   180 */   179,  197,  180,  130,  181,   30,  182,   17,  183,   20,
 /*   190 */   179,  204,  180,  171,  181,  174,  182,  174,  183,   20,
 /*   200 */   174,  231,  185,  174,  186,  231,  185,  174,  186,  174,
 /*   210 */    38,  225,  230,  174,   40,  225,  230,  174,  201,  174,
 /*   220 */   180,  174,  181,  174,  182,  174,  183,   20,   19,   18,
 /*   230 */   231,  185,  174,  186,  231,  185,  174,  186,   21,   24,
 /*   240 */   227,  230,    7,    8,  229,  230,  231,  185,  174,  186,
 /*   250 */   231,  185,  134,  186,  174,   57,  228,  230,  174,  174,
 /*   260 */   226,  230,   12,   11,   10,    9,  131,  128,  174,   59,
 /*   270 */    61,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    53,   54,   52,   56,   57,   58,   59,   60,   61,   62,
 /*    10 */    63,   64,    2,   53,   54,    5,   56,   55,   58,   59,
 /*    20 */    60,   61,   62,   63,   64,   39,   40,   41,   42,   19,
 /*    30 */    19,   21,   27,   23,   53,   54,   26,   56,   28,   29,
 /*    40 */    27,   60,   61,   62,   63,   64,   20,   37,   38,   53,
 /*    50 */    54,   25,   56,   67,   58,   59,   60,   61,   62,   63,
 /*    60 */    64,   53,   54,   46,   56,   50,   58,   59,   60,   61,
 /*    70 */    62,   63,   64,   53,   54,   27,   56,   48,   58,   59,
 /*    80 */    60,   61,   62,   63,   64,   53,   54,   18,   56,   27,
 /*    90 */    58,   59,   60,   61,   62,   63,   64,   53,   54,   24,
 /*   100 */    56,   65,   66,   18,   60,   61,   62,   63,   64,   53,
 /*   110 */    54,    0,   56,   53,   54,   19,   56,   61,   62,   63,
 /*   120 */    64,   61,   62,   63,   64,   53,   54,   27,   56,   33,
 /*   130 */    34,   35,   36,   61,   62,   63,   64,   53,   54,   27,
 /*   140 */    56,   30,   31,   32,   28,   61,   62,   63,   64,   43,
 /*   150 */    44,   45,   27,   47,   28,   49,   22,   51,   52,   25,
 /*   160 */    43,   44,   45,   20,   47,   27,   49,   21,   51,   52,
 /*   170 */    43,   44,   45,   68,   47,   21,   49,   27,   51,   52,
 /*   180 */    43,   44,   45,   27,   47,   21,   49,   27,   51,   52,
 /*   190 */    43,   44,   45,   17,   47,   68,   49,   68,   51,   52,
 /*   200 */    68,   53,   54,   68,   56,   53,   54,   68,   56,   68,
 /*   210 */    62,   63,   64,   68,   62,   63,   64,   68,   43,   68,
 /*   220 */    45,   68,   47,   68,   49,   68,   51,   52,    1,    2,
 /*   230 */    53,   54,   68,   56,   53,   54,   68,   56,    3,    4,
 /*   240 */    63,   64,    6,    7,   63,   64,   53,   54,   68,   56,
 /*   250 */    53,   54,   22,   56,   68,   25,   63,   64,   68,   68,
 /*   260 */    63,   64,    8,    9,   10,   11,   22,   22,   68,   25,
 /*   270 */    25,   68,   68,   68,   68,   68,   68,   68,   68,   68,
 /*   280 */    68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
 /*   290 */    68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
 /*   300 */    68,   68,   68,   68,   68,   68,   68,   39,   39,   39,
};
#define YY_SHIFT_COUNT    (64)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (254)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */   271,   10,   10,   10,   10,   10,   10,   10,   10,   10,
 /*    10 */    10,   10,   10,   96,   96,   96,   96,   96,   10,   10,
 /*    20 */    96,   10,   10,   10,   10,  111,    5,   11,   13,   48,
 /*    30 */    62,  254,  254,  254,  227,  227,  227,  235,  235,  227,
 /*    40 */   235,  227,  236,   26,  134,  230,  244,  245,   69,   75,
 /*    50 */    85,  100,  116,  112,  125,  143,  126,  138,  146,  150,
 /*    60 */   154,  156,  164,  160,  176,
};
#define YY_REDUCE_COUNT (30)
#define YY_REDUCE_MIN   (-53)
#define YY_REDUCE_MAX   (197)
static const short yy_reduce_ofst[] = {
 /*     0 */    36,  -53,  -40,   -4,    8,   20,   32,  -19,   44,   56,
 /*    10 */    60,   72,   84,  106,  117,  127,  137,  147,  148,  152,
 /*    20 */   175,  177,  181,  193,  197,  -14,  -38,  -50,   15,   29,
 /*    30 */    17,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   234,  172,  172,  172,  172,  172,  172,  172,  172,  172,
 /*    10 */   172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
 /*    20 */   172,  172,  172,  172,  172,  172,  172,  202,  172,  172,
 /*    30 */   172,  216,  214,  215,  217,  221,  220,  222,  224,  219,
 /*    40 */   223,  218,  213,  172,  172,  172,  172,  172,  172,  172,
 /*    50 */   172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
 /*    60 */   172,  172,  172,  172,  172,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  lemon_parseARG_SDECL                /* A place to hold %extra_argument */
  lemon_parseCTX_SDECL                /* A place to hold %extra_context */
  yyStackEntry *yystackEnd;           /* Last entry in the stack */
  yyStackEntry *yystack;              /* The parser stack */
  yyStackEntry yystk0[YYSTACKDEPTH];  /* Initial stack space */
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void lemon_parseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "PLUS",
  /*    2 */ "MINUS",
  /*    3 */ "SLASH",
  /*    4 */ "STAR",
  /*    5 */ "BANG",
  /*    6 */ "BANG_EQUAL",
  /*    7 */ "EQUAL_EQUAL",
  /*    8 */ "GREATER",
  /*    9 */ "GREATER_EQUAL",
  /*   10 */ "LESS",
  /*   11 */ "LESS_EQUAL",
  /*   12 */ "NOT",
  /*   13 */ "CARET",
  /*   14 */ "PERCENT",
  /*   15 */ "PIPE",
  /*   16 */ "AMPERSAND",
  /*   17 */ "SEMICOLON",
  /*   18 */ "COLON",
  /*   19 */ "LEFT_BRACKET",
  /*   20 */ "RIGHT_BRACKET",
  /*   21 */ "LEFT_BRACE",
  /*   22 */ "RIGHT_BRACE",
  /*   23 */ "LEFT_PAREN",
  /*   24 */ "RIGHT_PAREN",
  /*   25 */ "COMMA",
  /*   26 */ "STRING",
  /*   27 */ "IDENTIFIER",
  /*   28 */ "INTEGER",
  /*   29 */ "FLOAT",
  /*   30 */ "CREATE",
  /*   31 */ "DELETE",
  /*   32 */ "INSERT",
  /*   33 */ "STRUCT",
  /*   34 */ "UNION",
  /*   35 */ "ENUM",
  /*   36 */ "PRIM",
  /*   37 */ "TRUE",
  /*   38 */ "FALSE",
  /*   39 */ "query",
  /*   40 */ "create_decl",
  /*   41 */ "delete_decl",
  /*   42 */ "insert_decl",
  /*   43 */ "type",
  /*   44 */ "type_spec",
  /*   45 */ "enum_decl",
  /*   46 */ "enum_items",
  /*   47 */ "struct_decl",
  /*   48 */ "struct_items",
  /*   49 */ "union_decl",
  /*   50 */ "union_items",
  /*   51 */ "sarray_decl",
  /*   52 */ "sarray_dims",
  /*   53 */ "value",
  /*   54 */ "object_decl",
  /*   55 */ "object_items",
  /*   56 */ "array_decl",
  /*   57 */ "array_items",
  /*   58 */ "expression",
  /*   59 */ "equality",
  /*   60 */ "comparison",
  /*   61 */ "term",
  /*   62 */ "factor",
  /*   63 */ "unary",
  /*   64 */ "primary",
  /*   65 */ "main",
  /*   66 */ "in",
  /*   67 */ "state",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "state ::= query",
 /*   1 */ "query ::= delete_decl",
 /*   2 */ "query ::= create_decl",
 /*   3 */ "query ::= insert_decl",
 /*   4 */ "type_spec ::= type",
 /*   5 */ "type ::= enum_decl",
 /*   6 */ "type ::= struct_decl",
 /*   7 */ "type ::= union_decl",
 /*   8 */ "type ::= sarray_decl",
 /*   9 */ "type ::= PRIM",
 /*  10 */ "value ::= object_decl",
 /*  11 */ "value ::= array_decl",
 /*  12 */ "value ::= STRING",
 /*  13 */ "value ::= INTEGER",
 /*  14 */ "value ::= FLOAT",
 /*  15 */ "value ::= TRUE",
 /*  16 */ "value ::= FALSE",
 /*  17 */ "enum_decl ::= ENUM LEFT_BRACE enum_items RIGHT_BRACE",
 /*  18 */ "enum_items ::= IDENTIFIER",
 /*  19 */ "enum_items ::= enum_items COMMA IDENTIFIER",
 /*  20 */ "struct_decl ::= STRUCT LEFT_BRACE struct_items RIGHT_BRACE",
 /*  21 */ "struct_items ::= IDENTIFIER type_spec",
 /*  22 */ "struct_items ::= struct_items COMMA IDENTIFIER type_spec",
 /*  23 */ "union_decl ::= UNION LEFT_BRACE union_items RIGHT_BRACE",
 /*  24 */ "union_items ::= IDENTIFIER type_spec",
 /*  25 */ "union_items ::= union_items COMMA IDENTIFIER type_spec",
 /*  26 */ "sarray_decl ::= sarray_dims type",
 /*  27 */ "sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET",
 /*  28 */ "sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET sarray_dims",
 /*  29 */ "create_decl ::= CREATE IDENTIFIER type_spec",
 /*  30 */ "delete_decl ::= DELETE IDENTIFIER",
 /*  31 */ "insert_decl ::= INSERT IDENTIFIER INTEGER expression",
 /*  32 */ "object_decl ::= LEFT_BRACE object_items RIGHT_BRACE",
 /*  33 */ "object_items ::= IDENTIFIER COLON expression",
 /*  34 */ "object_items ::= object_items COMMA IDENTIFIER COLON expression",
 /*  35 */ "array_decl ::= LEFT_BRACKET array_items RIGHT_BRACKET",
 /*  36 */ "array_items ::= expression",
 /*  37 */ "array_items ::= array_items COMMA expression",
 /*  38 */ "expression ::= equality",
 /*  39 */ "equality ::= comparison",
 /*  40 */ "equality ::= equality EQUAL_EQUAL comparison",
 /*  41 */ "equality ::= equality BANG_EQUAL comparison",
 /*  42 */ "comparison ::= term",
 /*  43 */ "comparison ::= comparison GREATER term",
 /*  44 */ "comparison ::= comparison GREATER_EQUAL term",
 /*  45 */ "comparison ::= comparison LESS term",
 /*  46 */ "comparison ::= comparison LESS_EQUAL term",
 /*  47 */ "term ::= factor",
 /*  48 */ "term ::= term PLUS factor",
 /*  49 */ "term ::= term MINUS factor",
 /*  50 */ "factor ::= unary",
 /*  51 */ "factor ::= factor STAR unary",
 /*  52 */ "factor ::= factor SLASH unary",
 /*  53 */ "unary ::= BANG unary",
 /*  54 */ "unary ::= MINUS unary",
 /*  55 */ "unary ::= primary",
 /*  56 */ "primary ::= value",
 /*  57 */ "primary ::= LEFT_PAREN expression RIGHT_PAREN",
 /*  58 */ "main ::= in",
 /*  59 */ "in ::=",
 /*  60 */ "in ::= in state SEMICOLON",
};
#endif /* NDEBUG */


#if YYGROWABLESTACK
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int oldSize = 1 + (int)(p->yystackEnd - p->yystack);
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = oldSize*2 + 100;
  idx = (int)(p->yytos - p->yystack);
  if( p->yystack==p->yystk0 ){
    pNew = YYREALLOC(0, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
    memcpy(pNew, p->yystack, oldSize*sizeof(pNew[0]));
  }else{
    pNew = YYREALLOC(p->yystack, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
  }
  p->yystack = pNew;
  p->yytos = &p->yystack[idx];
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
            yyTracePrompt, oldSize, newSize);
  }
#endif
  p->yystackEnd = &p->yystack[newSize-1];
  return 0;
}
#endif /* YYGROWABLESTACK */

#if !YYGROWABLESTACK
/* For builds that do no have a growable stack, yyGrowStack always
** returns an error.
*/
# define yyGrowStack(X) 1
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to lemon_parseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void lemon_parseInit(void *yypRawParser lemon_parseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  lemon_parseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
  yypParser->yystack = yypParser->yystk0;
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
}

#ifndef lemon_parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to lemon_parse and lemon_parseFree.
*/
void *lemon_parseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) lemon_parseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    lemon_parseCTX_STORE
    lemon_parseInit(yypParser lemon_parseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* lemon_parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  lemon_parseARG_FETCH
  lemon_parseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void lemon_parseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;

  /* In-lined version of calling yy_pop_parser_stack() for each
  ** element left in the stack */
  yyStackEntry *yytos = pParser->yytos;
  while( yytos>pParser->yystack ){
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sPopping %s\n",
        yyTracePrompt,
        yyTokenName[yytos->major]);
    }
#endif
    if( yytos->major>=YY_MIN_DSTRCTR ){
      yy_destructor(pParser, yytos->major, &yytos->minor);
    }
    yytos--;
  }

#if YYGROWABLESTACK
  if( pParser->yystack!=pParser->yystk0 ) YYFREE(pParser->yystack);
#endif
}

#ifndef lemon_parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void lemon_parseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  lemon_parseFinalize(p);
  (*freeProc)(p);
}
#endif /* lemon_parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int lemon_parseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int lemon_parseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   lemon_parseARG_FETCH
   lemon_parseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   lemon_parseARG_STORE /* Suppress warning about unused %extra_argument var */
   lemon_parseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  lemon_parseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
  yytos = yypParser->yytos;
  if( yytos>yypParser->yystackEnd ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
    yytos = yypParser->yytos;
    assert( yytos <= yypParser->yystackEnd );
  }
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    67,  /* (0) state ::= query */
    39,  /* (1) query ::= delete_decl */
    39,  /* (2) query ::= create_decl */
    39,  /* (3) query ::= insert_decl */
    44,  /* (4) type_spec ::= type */
    43,  /* (5) type ::= enum_decl */
    43,  /* (6) type ::= struct_decl */
    43,  /* (7) type ::= union_decl */
    43,  /* (8) type ::= sarray_decl */
    43,  /* (9) type ::= PRIM */
    53,  /* (10) value ::= object_decl */
    53,  /* (11) value ::= array_decl */
    53,  /* (12) value ::= STRING */
    53,  /* (13) value ::= INTEGER */
    53,  /* (14) value ::= FLOAT */
    53,  /* (15) value ::= TRUE */
    53,  /* (16) value ::= FALSE */
    45,  /* (17) enum_decl ::= ENUM LEFT_BRACE enum_items RIGHT_BRACE */
    46,  /* (18) enum_items ::= IDENTIFIER */
    46,  /* (19) enum_items ::= enum_items COMMA IDENTIFIER */
    47,  /* (20) struct_decl ::= STRUCT LEFT_BRACE struct_items RIGHT_BRACE */
    48,  /* (21) struct_items ::= IDENTIFIER type_spec */
    48,  /* (22) struct_items ::= struct_items COMMA IDENTIFIER type_spec */
    49,  /* (23) union_decl ::= UNION LEFT_BRACE union_items RIGHT_BRACE */
    50,  /* (24) union_items ::= IDENTIFIER type_spec */
    50,  /* (25) union_items ::= union_items COMMA IDENTIFIER type_spec */
    51,  /* (26) sarray_decl ::= sarray_dims type */
    52,  /* (27) sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET */
    52,  /* (28) sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET sarray_dims */
    40,  /* (29) create_decl ::= CREATE IDENTIFIER type_spec */
    41,  /* (30) delete_decl ::= DELETE IDENTIFIER */
    42,  /* (31) insert_decl ::= INSERT IDENTIFIER INTEGER expression */
    54,  /* (32) object_decl ::= LEFT_BRACE object_items RIGHT_BRACE */
    55,  /* (33) object_items ::= IDENTIFIER COLON expression */
    55,  /* (34) object_items ::= object_items COMMA IDENTIFIER COLON expression */
    56,  /* (35) array_decl ::= LEFT_BRACKET array_items RIGHT_BRACKET */
    57,  /* (36) array_items ::= expression */
    57,  /* (37) array_items ::= array_items COMMA expression */
    58,  /* (38) expression ::= equality */
    59,  /* (39) equality ::= comparison */
    59,  /* (40) equality ::= equality EQUAL_EQUAL comparison */
    59,  /* (41) equality ::= equality BANG_EQUAL comparison */
    60,  /* (42) comparison ::= term */
    60,  /* (43) comparison ::= comparison GREATER term */
    60,  /* (44) comparison ::= comparison GREATER_EQUAL term */
    60,  /* (45) comparison ::= comparison LESS term */
    60,  /* (46) comparison ::= comparison LESS_EQUAL term */
    61,  /* (47) term ::= factor */
    61,  /* (48) term ::= term PLUS factor */
    61,  /* (49) term ::= term MINUS factor */
    62,  /* (50) factor ::= unary */
    62,  /* (51) factor ::= factor STAR unary */
    62,  /* (52) factor ::= factor SLASH unary */
    63,  /* (53) unary ::= BANG unary */
    63,  /* (54) unary ::= MINUS unary */
    63,  /* (55) unary ::= primary */
    64,  /* (56) primary ::= value */
    64,  /* (57) primary ::= LEFT_PAREN expression RIGHT_PAREN */
    65,  /* (58) main ::= in */
    66,  /* (59) in ::= */
    66,  /* (60) in ::= in state SEMICOLON */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) state ::= query */
   -1,  /* (1) query ::= delete_decl */
   -1,  /* (2) query ::= create_decl */
   -1,  /* (3) query ::= insert_decl */
   -1,  /* (4) type_spec ::= type */
   -1,  /* (5) type ::= enum_decl */
   -1,  /* (6) type ::= struct_decl */
   -1,  /* (7) type ::= union_decl */
   -1,  /* (8) type ::= sarray_decl */
   -1,  /* (9) type ::= PRIM */
   -1,  /* (10) value ::= object_decl */
   -1,  /* (11) value ::= array_decl */
   -1,  /* (12) value ::= STRING */
   -1,  /* (13) value ::= INTEGER */
   -1,  /* (14) value ::= FLOAT */
   -1,  /* (15) value ::= TRUE */
   -1,  /* (16) value ::= FALSE */
   -4,  /* (17) enum_decl ::= ENUM LEFT_BRACE enum_items RIGHT_BRACE */
   -1,  /* (18) enum_items ::= IDENTIFIER */
   -3,  /* (19) enum_items ::= enum_items COMMA IDENTIFIER */
   -4,  /* (20) struct_decl ::= STRUCT LEFT_BRACE struct_items RIGHT_BRACE */
   -2,  /* (21) struct_items ::= IDENTIFIER type_spec */
   -4,  /* (22) struct_items ::= struct_items COMMA IDENTIFIER type_spec */
   -4,  /* (23) union_decl ::= UNION LEFT_BRACE union_items RIGHT_BRACE */
   -2,  /* (24) union_items ::= IDENTIFIER type_spec */
   -4,  /* (25) union_items ::= union_items COMMA IDENTIFIER type_spec */
   -2,  /* (26) sarray_decl ::= sarray_dims type */
   -3,  /* (27) sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET */
   -4,  /* (28) sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET sarray_dims */
   -3,  /* (29) create_decl ::= CREATE IDENTIFIER type_spec */
   -2,  /* (30) delete_decl ::= DELETE IDENTIFIER */
   -4,  /* (31) insert_decl ::= INSERT IDENTIFIER INTEGER expression */
   -3,  /* (32) object_decl ::= LEFT_BRACE object_items RIGHT_BRACE */
   -3,  /* (33) object_items ::= IDENTIFIER COLON expression */
   -5,  /* (34) object_items ::= object_items COMMA IDENTIFIER COLON expression */
   -3,  /* (35) array_decl ::= LEFT_BRACKET array_items RIGHT_BRACKET */
   -1,  /* (36) array_items ::= expression */
   -3,  /* (37) array_items ::= array_items COMMA expression */
   -1,  /* (38) expression ::= equality */
   -1,  /* (39) equality ::= comparison */
   -3,  /* (40) equality ::= equality EQUAL_EQUAL comparison */
   -3,  /* (41) equality ::= equality BANG_EQUAL comparison */
   -1,  /* (42) comparison ::= term */
   -3,  /* (43) comparison ::= comparison GREATER term */
   -3,  /* (44) comparison ::= comparison GREATER_EQUAL term */
   -3,  /* (45) comparison ::= comparison LESS term */
   -3,  /* (46) comparison ::= comparison LESS_EQUAL term */
   -1,  /* (47) term ::= factor */
   -3,  /* (48) term ::= term PLUS factor */
   -3,  /* (49) term ::= term MINUS factor */
   -1,  /* (50) factor ::= unary */
   -3,  /* (51) factor ::= factor STAR unary */
   -3,  /* (52) factor ::= factor SLASH unary */
   -2,  /* (53) unary ::= BANG unary */
   -2,  /* (54) unary ::= MINUS unary */
   -1,  /* (55) unary ::= primary */
   -1,  /* (56) primary ::= value */
   -3,  /* (57) primary ::= LEFT_PAREN expression RIGHT_PAREN */
   -1,  /* (58) main ::= in */
    0,  /* (59) in ::= */
   -3,  /* (60) in ::= in state SEMICOLON */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  lemon_parseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  lemon_parseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  lemon_parseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* state ::= query */
#line 129 "./tools/lemon/parser.y"
{
    res->result = yymsp[0].minor.yy115;
    res->ready = true;
}
#line 1212 "./tools/lemon/parser.c"
        break;
      case 1: /* query ::= delete_decl */
      case 2: /* query ::= create_decl */ yytestcase(yyruleno==2);
      case 3: /* query ::= insert_decl */ yytestcase(yyruleno==3);
#line 135 "./tools/lemon/parser.y"
{
    yylhsminor.yy115 = yymsp[0].minor.yy115;
}
#line 1221 "./tools/lemon/parser.c"
  yymsp[0].minor.yy115 = yylhsminor.yy115;
        break;
      case 4: /* type_spec ::= type */
#line 148 "./tools/lemon/parser.y"
{ yylhsminor.yy123 = yymsp[0].minor.yy123; }
#line 1227 "./tools/lemon/parser.c"
  yymsp[0].minor.yy123 = yylhsminor.yy123;
        break;
      case 5: /* type ::= enum_decl */
#line 150 "./tools/lemon/parser.y"
{
    yylhsminor.yy123 = (type){ .type = T_ENUM };
    if (enb_build(&yylhsminor.yy123.en, &yymsp[0].minor.yy128, res->e)) break;
}
#line 1236 "./tools/lemon/parser.c"
  yymsp[0].minor.yy123 = yylhsminor.yy123;
        break;
      case 6: /* type ::= struct_decl */
#line 155 "./tools/lemon/parser.y"
{
    yylhsminor.yy123 = (type){ .type = T_STRUCT };
    if (kvb_struct_t_build(&yylhsminor.yy123.st, &yymsp[0].minor.yy8, res->e)) break;
}
#line 1245 "./tools/lemon/parser.c"
  yymsp[0].minor.yy123 = yylhsminor.yy123;
        break;
      case 7: /* type ::= union_decl */
#line 160 "./tools/lemon/parser.y"
{
    yylhsminor.yy123 = (type){ .type = T_UNION };
    if (kvb_union_t_build(&yylhsminor.yy123.un, &yymsp[0].minor.yy8, res->e)) break;
}
#line 1254 "./tools/lemon/parser.c"
  yymsp[0].minor.yy123 = yylhsminor.yy123;
        break;
      case 8: /* type ::= sarray_decl */
#line 165 "./tools/lemon/parser.y"
{
    yylhsminor.yy123 = (type){ .type = T_SARRAY };
    if (sab_build(&yylhsminor.yy123.sa, &yymsp[0].minor.yy117, res->e)) break;
}
#line 1263 "./tools/lemon/parser.c"
  yymsp[0].minor.yy123 = yylhsminor.yy123;
        break;
      case 9: /* type ::= PRIM */
#line 170 "./tools/lemon/parser.y"
{
  yylhsminor.yy123 = (type){ 
    .type = T_PRIM,
    .p = yymsp[0].minor.yy0.prim,
  };
}
#line 1274 "./tools/lemon/parser.c"
  yymsp[0].minor.yy123 = yylhsminor.yy123;
        break;
      case 10: /* value ::= object_decl */
#line 178 "./tools/lemon/parser.y"
{
  yylhsminor.yy134 = (value){ .type = VT_OBJECT };
  if(objb_build(&yylhsminor.yy134.obj, &yymsp[0].minor.yy114, res->e)) break;
}
#line 1283 "./tools/lemon/parser.c"
  yymsp[0].minor.yy134 = yylhsminor.yy134;
        break;
      case 11: /* value ::= array_decl */
#line 183 "./tools/lemon/parser.y"
{
  yylhsminor.yy134 = (value){ .type = VT_ARRAY };
  if(arb_build(&yylhsminor.yy134.arr, &yymsp[0].minor.yy22, res->e)) break;
}
#line 1292 "./tools/lemon/parser.c"
  yymsp[0].minor.yy134 = yylhsminor.yy134;
        break;
      case 12: /* value ::= STRING */
#line 189 "./tools/lemon/parser.y"
{
  yylhsminor.yy134 = value_string_create(yymsp[0].minor.yy0.str); 
}
#line 1300 "./tools/lemon/parser.c"
  yymsp[0].minor.yy134 = yylhsminor.yy134;
        break;
      case 13: /* value ::= INTEGER */
#line 193 "./tools/lemon/parser.y"
{
  yylhsminor.yy134 = value_number_create(yymsp[0].minor.yy0.integer); 
}
#line 1308 "./tools/lemon/parser.c"
  yymsp[0].minor.yy134 = yylhsminor.yy134;
        break;
      case 14: /* value ::= FLOAT */
#line 197 "./tools/lemon/parser.y"
{
  yylhsminor.yy134 = value_number_create(yymsp[0].minor.yy0.floating); 
}
#line 1316 "./tools/lemon/parser.c"
  yymsp[0].minor.yy134 = yylhsminor.yy134;
        break;
      case 15: /* value ::= TRUE */
#line 203 "./tools/lemon/parser.y"
{
  yymsp[0].minor.yy134 = value_true_create(); 
}
#line 1324 "./tools/lemon/parser.c"
        break;
      case 16: /* value ::= FALSE */
#line 207 "./tools/lemon/parser.y"
{
  yymsp[0].minor.yy134 = value_false_create(); 
}
#line 1331 "./tools/lemon/parser.c"
        break;
      case 17: /* enum_decl ::= ENUM LEFT_BRACE enum_items RIGHT_BRACE */
#line 214 "./tools/lemon/parser.y"
{ yymsp[-3].minor.yy128 = yymsp[-1].minor.yy128; }
#line 1336 "./tools/lemon/parser.c"
        break;
      case 18: /* enum_items ::= IDENTIFIER */
#line 217 "./tools/lemon/parser.y"
{
    yylhsminor.yy128 = enb_create(res->work, res->dest);
    if (enb_accept_key(&yylhsminor.yy128, yymsp[0].minor.yy0.str, res->e)) break;
}
#line 1344 "./tools/lemon/parser.c"
  yymsp[0].minor.yy128 = yylhsminor.yy128;
        break;
      case 19: /* enum_items ::= enum_items COMMA IDENTIFIER */
#line 223 "./tools/lemon/parser.y"
{
    yylhsminor.yy128 = yymsp[-2].minor.yy128;
    if (enb_accept_key(&yylhsminor.yy128, yymsp[0].minor.yy0.str, res->e)) break;
}
#line 1353 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy128 = yylhsminor.yy128;
        break;
      case 20: /* struct_decl ::= STRUCT LEFT_BRACE struct_items RIGHT_BRACE */
      case 23: /* union_decl ::= UNION LEFT_BRACE union_items RIGHT_BRACE */ yytestcase(yyruleno==23);
#line 231 "./tools/lemon/parser.y"
{ yymsp[-3].minor.yy8 = yymsp[-1].minor.yy8; }
#line 1360 "./tools/lemon/parser.c"
        break;
      case 21: /* struct_items ::= IDENTIFIER type_spec */
#line 235 "./tools/lemon/parser.y"
{
    yylhsminor.yy8 = kvb_create(res->work, res->dest);                 /* <-- was “yylhsminor.yy8 = B;” (undefined) */
    if (kvb_accept_key (&yylhsminor.yy8, yymsp[-1].minor.yy0.str, res->e)) break;
    if (kvb_accept_type(&yylhsminor.yy8, yymsp[0].minor.yy123,       res->e)) break;
}
#line 1369 "./tools/lemon/parser.c"
  yymsp[-1].minor.yy8 = yylhsminor.yy8;
        break;
      case 22: /* struct_items ::= struct_items COMMA IDENTIFIER type_spec */
      case 25: /* union_items ::= union_items COMMA IDENTIFIER type_spec */ yytestcase(yyruleno==25);
#line 243 "./tools/lemon/parser.y"
{
    yylhsminor.yy8 = yymsp[-3].minor.yy8;
    if (kvb_accept_key (&yylhsminor.yy8, yymsp[-1].minor.yy0.str, res->e)) break;
    if (kvb_accept_type(&yylhsminor.yy8, yymsp[0].minor.yy123,       res->e)) break;
}
#line 1380 "./tools/lemon/parser.c"
  yymsp[-3].minor.yy8 = yylhsminor.yy8;
        break;
      case 24: /* union_items ::= IDENTIFIER type_spec */
#line 256 "./tools/lemon/parser.y"
{
    yylhsminor.yy8 = kvb_create(res->work, res->dest);
    if (kvb_accept_key (&yylhsminor.yy8, yymsp[-1].minor.yy0.str, res->e)) break;
    if (kvb_accept_type(&yylhsminor.yy8, yymsp[0].minor.yy123,       res->e)) break;
}
#line 1390 "./tools/lemon/parser.c"
  yymsp[-1].minor.yy8 = yylhsminor.yy8;
        break;
      case 26: /* sarray_decl ::= sarray_dims type */
#line 276 "./tools/lemon/parser.y"
{  
  if (sab_accept_type(&yymsp[-1].minor.yy117, yymsp[0].minor.yy123, res->e)) break;
  yylhsminor.yy117 = yymsp[-1].minor.yy117; 
}
#line 1399 "./tools/lemon/parser.c"
  yymsp[-1].minor.yy117 = yylhsminor.yy117;
        break;
      case 27: /* sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET */
#line 282 "./tools/lemon/parser.y"
{ 
  yymsp[-2].minor.yy117 = sab_create(res->work, res->dest);
  if (sab_accept_dim(&yymsp[-2].minor.yy117, yymsp[-1].minor.yy0.integer, res->e)) break;
}
#line 1408 "./tools/lemon/parser.c"
        break;
      case 28: /* sarray_dims ::= LEFT_BRACKET INTEGER RIGHT_BRACKET sarray_dims */
#line 288 "./tools/lemon/parser.y"
{
  if (sab_accept_dim(&yymsp[0].minor.yy117, yymsp[-2].minor.yy0.integer, res->e)) break;
  yymsp[-3].minor.yy117 = yymsp[0].minor.yy117;
}
#line 1416 "./tools/lemon/parser.c"
        break;
      case 29: /* create_decl ::= CREATE IDENTIFIER type_spec */
#line 296 "./tools/lemon/parser.y"
{
    yylhsminor.yy115 = yymsp[-2].minor.yy0.q;

    // Build the builder
    create_builder tmp = crb_create();

    // Accept
    if (crb_accept_string(&tmp, yymsp[-1].minor.yy0.str, res->e)) break;
    if (crb_accept_type(&tmp, yymsp[0].minor.yy123, res->e)) break;

    // Build the query
    if (crb_build(yylhsminor.yy115.create, &tmp, res->e)) break; 
}
#line 1433 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy115 = yylhsminor.yy115;
        break;
      case 30: /* delete_decl ::= DELETE IDENTIFIER */
#line 313 "./tools/lemon/parser.y"
{
    yylhsminor.yy115 = yymsp[-1].minor.yy0.q;

    // Build the builder
    delete_builder tmp = dltb_create();

    // Accept
    if (dltb_accept_string(&tmp, yymsp[0].minor.yy0.str, res->e)) break;

    // Build the query
    if (dltb_build(yylhsminor.yy115.delete, &tmp, res->e)) break; 
}
#line 1450 "./tools/lemon/parser.c"
  yymsp[-1].minor.yy115 = yylhsminor.yy115;
        break;
      case 31: /* insert_decl ::= INSERT IDENTIFIER INTEGER expression */
#line 329 "./tools/lemon/parser.y"
{
    yylhsminor.yy115 = yymsp[-3].minor.yy0.q;

    // Build the builder
    insert_builder tmp = inb_create();

    // Evaluate expression 
    value v;
    if(expr_evaluate(&v, yymsp[0].minor.yy82, res->work, res->e)) break;

    // Accept
    if (inb_accept_string(&tmp, yymsp[-2].minor.yy0.str, res->e)) break;
    if (inb_accept_value(&tmp, v, res->e)) break;
    if (inb_accept_start(&tmp, yymsp[-1].minor.yy0.integer, res->e)) break;

    // Build the query
    if (inb_build(yylhsminor.yy115.insert, &tmp, res->e)) break; 
}
#line 1473 "./tools/lemon/parser.c"
  yymsp[-3].minor.yy115 = yylhsminor.yy115;
        break;
      case 32: /* object_decl ::= LEFT_BRACE object_items RIGHT_BRACE */
#line 351 "./tools/lemon/parser.y"
{ yymsp[-2].minor.yy114 = yymsp[-1].minor.yy114; }
#line 1479 "./tools/lemon/parser.c"
        break;
      case 33: /* object_items ::= IDENTIFIER COLON expression */
#line 355 "./tools/lemon/parser.y"
{
    // Evaluate expression 
    value v;
    if(expr_evaluate(&v, yymsp[0].minor.yy82, res->work, res->e)) break;

    yylhsminor.yy114 = objb_create(res->work, res->dest);
    if (objb_accept_string(&yylhsminor.yy114, yymsp[-2].minor.yy0.str, res->e)) break;
    if (objb_accept_value(&yylhsminor.yy114, v,       res->e)) break;
}
#line 1492 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy114 = yylhsminor.yy114;
        break;
      case 34: /* object_items ::= object_items COMMA IDENTIFIER COLON expression */
#line 367 "./tools/lemon/parser.y"
{
    // Evaluate expression 
    value v;
    if(expr_evaluate(&v, yymsp[0].minor.yy82, res->work, res->e)) break;

    yylhsminor.yy114 = yymsp[-4].minor.yy114;
    if (objb_accept_string(&yylhsminor.yy114, yymsp[-2].minor.yy0.str, res->e)) break;
    if (objb_accept_value(&yylhsminor.yy114, v,       res->e)) break;
}
#line 1506 "./tools/lemon/parser.c"
  yymsp[-4].minor.yy114 = yylhsminor.yy114;
        break;
      case 35: /* array_decl ::= LEFT_BRACKET array_items RIGHT_BRACKET */
#line 380 "./tools/lemon/parser.y"
{  yymsp[-2].minor.yy22 = yymsp[-1].minor.yy22; }
#line 1512 "./tools/lemon/parser.c"
        break;
      case 36: /* array_items ::= expression */
#line 384 "./tools/lemon/parser.y"
{ 
  // Evaluate expression 
  value v;
  if(expr_evaluate(&v, yymsp[0].minor.yy82, res->work, res->e)) break;

  yylhsminor.yy22 = arb_create(res->work, res->dest);
  if (arb_accept_value(&yylhsminor.yy22, v, res->e)) break;
}
#line 1524 "./tools/lemon/parser.c"
  yymsp[0].minor.yy22 = yylhsminor.yy22;
        break;
      case 37: /* array_items ::= array_items COMMA expression */
#line 395 "./tools/lemon/parser.y"
{
  // Evaluate expression 
  value v;
  if(expr_evaluate(&v, yymsp[0].minor.yy82, res->work, res->e)) break;

  yylhsminor.yy22 = yymsp[-2].minor.yy22;
  if (arb_accept_value(&yylhsminor.yy22, v, res->e)) break;
}
#line 1537 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy22 = yylhsminor.yy22;
        break;
      case 38: /* expression ::= equality */
      case 39: /* equality ::= comparison */ yytestcase(yyruleno==39);
      case 42: /* comparison ::= term */ yytestcase(yyruleno==42);
      case 47: /* term ::= factor */ yytestcase(yyruleno==47);
      case 50: /* factor ::= unary */ yytestcase(yyruleno==50);
      case 55: /* unary ::= primary */ yytestcase(yyruleno==55);
#line 417 "./tools/lemon/parser.y"
{
  yylhsminor.yy82 = yymsp[0].minor.yy82;
}
#line 1550 "./tools/lemon/parser.c"
  yymsp[0].minor.yy82 = yylhsminor.yy82;
        break;
      case 40: /* equality ::= equality EQUAL_EQUAL comparison */
#line 427 "./tools/lemon/parser.y"
{
  yylhsminor.yy82 = lmalloc(res->work, 1, sizeof *yylhsminor.yy82);
  if (yylhsminor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yylhsminor.yy82 = create_binary_expr(yymsp[-2].minor.yy82, TT_EQUAL_EQUAL, yymsp[0].minor.yy82);
}
#line 1563 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy82 = yylhsminor.yy82;
        break;
      case 41: /* equality ::= equality BANG_EQUAL comparison */
#line 436 "./tools/lemon/parser.y"
{
  yylhsminor.yy82 = lmalloc(res->work, 1, sizeof *yylhsminor.yy82);
  if (yylhsminor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yylhsminor.yy82 = create_binary_expr(yymsp[-2].minor.yy82, TT_BANG_EQUAL, yymsp[0].minor.yy82);
}
#line 1576 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy82 = yylhsminor.yy82;
        break;
      case 43: /* comparison ::= comparison GREATER term */
#line 451 "./tools/lemon/parser.y"
{
  yylhsminor.yy82 = lmalloc(res->work, 1, sizeof *yylhsminor.yy82);
  if (yylhsminor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yylhsminor.yy82 = create_binary_expr(yymsp[-2].minor.yy82, TT_GREATER, yymsp[0].minor.yy82);
}
#line 1589 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy82 = yylhsminor.yy82;
        break;
      case 44: /* comparison ::= comparison GREATER_EQUAL term */
#line 460 "./tools/lemon/parser.y"
{
  yylhsminor.yy82 = lmalloc(res->work, 1, sizeof *yylhsminor.yy82);
  if (yylhsminor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yylhsminor.yy82 = create_binary_expr(yymsp[-2].minor.yy82, TT_GREATER_EQUAL, yymsp[0].minor.yy82);
}
#line 1602 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy82 = yylhsminor.yy82;
        break;
      case 45: /* comparison ::= comparison LESS term */
#line 469 "./tools/lemon/parser.y"
{
  yylhsminor.yy82 = lmalloc(res->work, 1, sizeof *yylhsminor.yy82);
  if (yylhsminor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yylhsminor.yy82 = create_binary_expr(yymsp[-2].minor.yy82, TT_LESS, yymsp[0].minor.yy82);
}
#line 1615 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy82 = yylhsminor.yy82;
        break;
      case 46: /* comparison ::= comparison LESS_EQUAL term */
#line 478 "./tools/lemon/parser.y"
{
  yylhsminor.yy82 = lmalloc(res->work, 1, sizeof *yylhsminor.yy82);
  if (yylhsminor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yylhsminor.yy82 = create_binary_expr(yymsp[-2].minor.yy82, TT_LESS_EQUAL, yymsp[0].minor.yy82);
}
#line 1628 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy82 = yylhsminor.yy82;
        break;
      case 48: /* term ::= term PLUS factor */
#line 493 "./tools/lemon/parser.y"
{
  yylhsminor.yy82 = lmalloc(res->work, 1, sizeof *yylhsminor.yy82);
  if (yylhsminor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yylhsminor.yy82 = create_binary_expr(yymsp[-2].minor.yy82, TT_PLUS, yymsp[0].minor.yy82);
}
#line 1641 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy82 = yylhsminor.yy82;
        break;
      case 49: /* term ::= term MINUS factor */
#line 502 "./tools/lemon/parser.y"
{
  yylhsminor.yy82 = lmalloc(res->work, 1, sizeof *yylhsminor.yy82);
  if (yylhsminor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yylhsminor.yy82 = create_binary_expr(yymsp[-2].minor.yy82, TT_MINUS, yymsp[0].minor.yy82);
}
#line 1654 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy82 = yylhsminor.yy82;
        break;
      case 51: /* factor ::= factor STAR unary */
#line 517 "./tools/lemon/parser.y"
{
  yylhsminor.yy82 = lmalloc(res->work, 1, sizeof *yylhsminor.yy82);
  if (yylhsminor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yylhsminor.yy82 = create_binary_expr(yymsp[-2].minor.yy82, TT_STAR, yymsp[0].minor.yy82);
}
#line 1667 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy82 = yylhsminor.yy82;
        break;
      case 52: /* factor ::= factor SLASH unary */
#line 526 "./tools/lemon/parser.y"
{
  yylhsminor.yy82 = lmalloc(res->work, 1, sizeof *yylhsminor.yy82);
  if (yylhsminor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yylhsminor.yy82 = create_binary_expr(yymsp[-2].minor.yy82, TT_SLASH, yymsp[0].minor.yy82);
}
#line 1680 "./tools/lemon/parser.c"
  yymsp[-2].minor.yy82 = yylhsminor.yy82;
        break;
      case 53: /* unary ::= BANG unary */
#line 537 "./tools/lemon/parser.y"
{
  yymsp[-1].minor.yy82 = lmalloc(res->work, 1, sizeof *yymsp[-1].minor.yy82);
  if (yymsp[-1].minor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  /* fixed argument order: op first, expr second */
  *yymsp[-1].minor.yy82 = create_unary_expr(yymsp[0].minor.yy82, TT_BANG);
}
#line 1694 "./tools/lemon/parser.c"
        break;
      case 54: /* unary ::= MINUS unary */
#line 547 "./tools/lemon/parser.y"
{
  yymsp[-1].minor.yy82 = lmalloc(res->work, 1, sizeof *yymsp[-1].minor.yy82);
  if (yymsp[-1].minor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yymsp[-1].minor.yy82 = create_unary_expr(yymsp[0].minor.yy82, TT_MINUS);
}
#line 1706 "./tools/lemon/parser.c"
        break;
      case 56: /* primary ::= value */
#line 561 "./tools/lemon/parser.y"
{
  yylhsminor.yy82 = lmalloc(res->work, 1, sizeof *yylhsminor.yy82);
  if (yylhsminor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yylhsminor.yy82 = create_value_expr(yymsp[0].minor.yy134);
}
#line 1718 "./tools/lemon/parser.c"
  yymsp[0].minor.yy82 = yylhsminor.yy82;
        break;
      case 57: /* primary ::= LEFT_PAREN expression RIGHT_PAREN */
#line 570 "./tools/lemon/parser.y"
{
  yymsp[-2].minor.yy82 = lmalloc(res->work, 1, sizeof *yymsp[-2].minor.yy82);
  if (yymsp[-2].minor.yy82 == NULL) {
    error_causef(res->e, ERR_NOMEM, "Failed to allocate expression");
    break;
  }
  *yymsp[-2].minor.yy82 = create_grouping_expr(yymsp[-1].minor.yy82);
}
#line 1731 "./tools/lemon/parser.c"
        break;
      default:
      /* (58) main ::= in */ yytestcase(yyruleno==58);
      /* (59) in ::= */ yytestcase(yyruleno==59);
      /* (60) in ::= in state SEMICOLON */ yytestcase(yyruleno==60);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  lemon_parseARG_FETCH
  lemon_parseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 116 "./tools/lemon/parser.y"

  error_causef(
    res->e, 
    ERR_SYNTAX, 
    "Parser error at index: %d\n", res->tnum);
#line 1784 "./tools/lemon/parser.c"
/************ End %parse_failure code *****************************************/
  lemon_parseARG_STORE /* Suppress warning about unused %extra_argument variable */
  lemon_parseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  lemon_parseTOKENTYPE yyminor         /* The minor type of the error token */
){
  lemon_parseARG_FETCH
  lemon_parseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 108 "./tools/lemon/parser.y"

  error_causef(
    res->e, 
    ERR_SYNTAX, 
    "Syntax error at token: %s at index: %d", 
    tt_tostr(yyminor.type), res->tnum);
#line 1810 "./tools/lemon/parser.c"
/************ End %syntax_error code ******************************************/
  lemon_parseARG_STORE /* Suppress warning about unused %extra_argument variable */
  lemon_parseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  lemon_parseARG_FETCH
  lemon_parseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  lemon_parseARG_STORE /* Suppress warning about unused %extra_argument variable */
  lemon_parseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "lemon_parseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void lemon_parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  lemon_parseTOKENTYPE yyminor       /* The value for the token */
  lemon_parseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  lemon_parseCTX_FETCH
  lemon_parseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
        if( yypParser->yytos>=yypParser->yystackEnd ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor lemon_parseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int lemon_parseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
