<!-- Autogenerated with command: ./scripts/generate_docs.py -->
<script setup lang="ts">
import NumstoreSection from "./Numstore/Index.vue";
import NumstoreWhatIsNumstoreSection from "./Numstore/What is Numstore_/Index.vue";
import NumstoreWhatIsNumstoreContextSection from "./Numstore/What is Numstore_/Context/Index.vue";
import NumstoreWhatIsNumstoreHistoricalPrecedentMachineLearningSection from "./Numstore/What is Numstore_/Historical Precedent_ Machine Learning/Index.vue";
import NumstoreWhatIsNumstoreHistoricalPrecedentUSIntelligenceCommunitySection from "./Numstore/What is Numstore_/Historical Precedent_ US Intelligence Community/Index.vue";
import NumstoreWhatIsNumstoreOtherScientificAndEngineeringFormatsSection from "./Numstore/What is Numstore_/Other Scientific and Engineering Formats/Index.vue";
import NumstoreWhatIsNumstoreNumstoreSPositioningSection from "./Numstore/What is Numstore_/Numstore's Positioning/Index.vue";
import NumstoreUsecasesSection from "./Numstore/Usecases/Index.vue";
import NumstoreComparisonWithOtherDatabasesSection from "./Numstore/Comparison with other Databases/Index.vue";
import NumstoreMetricsAndNumbersSection from "./Numstore/Metrics and Numbers/Index.vue";
import NumstoreWhatCanNumstoreNotDoSection from "./Numstore/What can Numstore not do_/Index.vue";
import NumstoreFeaturesCheatSheetSection from "./Numstore/Features Cheat sheet/Index.vue";
import NumstoreFeaturesOverviewSection from "./Numstore/Features Overview/Index.vue";
import NumstoreGettingStartedSection from "./Numstore/Getting Started/Index.vue";
import NumstoreGettingStartedLinuxSection from "./Numstore/Getting Started/Linux/Index.vue";
import NumstoreGettingStartedWindowsSection from "./Numstore/Getting Started/Windows/Index.vue";
import NumstoreGettingStartedMacSection from "./Numstore/Getting Started/Mac/Index.vue";
import NumstoreGettingStartedMainConceptsSection from "./Numstore/Getting Started/Main Concepts/Index.vue";
import NumstoreVocabularySection from "./Numstore/Vocabulary/Index.vue";
import NumstoreVocabularyVariableSection from "./Numstore/Vocabulary/Variable/Index.vue";
import NumstoreVocabularyTypeSection from "./Numstore/Vocabulary/Type/Index.vue";
import NumstoreVocabularyArraySection from "./Numstore/Vocabulary/Array/Index.vue";
import NumstoreTypesSection from "./Numstore/Types/Index.vue";
import NumstoreTypesPrimitiveSection from "./Numstore/Types/Primitive/Index.vue";
import NumstoreTypesStructSection from "./Numstore/Types/Struct/Index.vue";
import NumstoreTypesUnionSection from "./Numstore/Types/Union/Index.vue";
import NumstoreTypesEnumSection from "./Numstore/Types/Enum/Index.vue";
import NumstoreTypesArraySection from "./Numstore/Types/Array/Index.vue";
import NumstoreVariableOperationsSection from "./Numstore/Variable Operations/Index.vue";
import NumstoreVariableOperationsSummarySection from "./Numstore/Variable Operations/Summary/Index.vue";
import NumstoreVariableOperationsCreateSection from "./Numstore/Variable Operations/Create/Index.vue";
import NumstoreVariableOperationsDeleteSection from "./Numstore/Variable Operations/Delete/Index.vue";
import NumstoreVariableOperationsInsertSection from "./Numstore/Variable Operations/Insert/Index.vue";
import NumstoreVariableOperationsRemoveSection from "./Numstore/Variable Operations/Remove/Index.vue";
import NumstoreVariableOperationsAppendSection from "./Numstore/Variable Operations/Append/Index.vue";
import NumstoreVariableOperationsTakeSection from "./Numstore/Variable Operations/Take/Index.vue";
import NumstoreVariableOperationsUpdateSection from "./Numstore/Variable Operations/Update/Index.vue";
import NumstoreConfigurationSection from "./Numstore/Configuration/Index.vue";
import NumstoreConfigurationVariableLevelSection from "./Numstore/Configuration/Variable Level/Index.vue";
import NumstoreConfigurationVariableLevelWindowedSection from "./Numstore/Configuration/Variable Level/Windowed/Index.vue";
import NumstoreConfigurationSystemLevelSection from "./Numstore/Configuration/System Level/Index.vue";
import NumstoreConfigurationSystemLevelNumberOfThreadsSection from "./Numstore/Configuration/System Level/Number of Threads/Index.vue";
import NumstoreConfigurationSystemLevelPageSizeSection from "./Numstore/Configuration/System Level/Page Size/Index.vue";
import NumstoreConfigurationSystemLevelMemoryLimitsSection from "./Numstore/Configuration/System Level/Memory Limits/Index.vue";
import NumstoreConfigurationSystemLevelMemoryLimitsBufferPoolSection from "./Numstore/Configuration/System Level/Memory Limits/Buffer Pool/Index.vue";
import NumstoreApplicationProgrammingInterfacesSection from "./Numstore/Application Programming Interfaces/Index.vue";
import NumstoreApplicationProgrammingInterfacesNumstoreCLibrarySection from "./Numstore/Application Programming Interfaces/Numstore C Library/Index.vue";
import NumstoreApplicationProgrammingInterfacesCommandLineInterfaceCLISection from "./Numstore/Application Programming Interfaces/Command Line Interface (CLI)/Index.vue";
import NumstoreApplicationProgrammingInterfacesTCPSection from "./Numstore/Application Programming Interfaces/TCP/Index.vue";
</script>

<template>
  <div class="prose">
    <h1>Table of Contents</h1>
<ul class="list-disc ml-6">
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-numstore">Numstore</a></li>
<ul class="list-disc ml-6">
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-what-is-numstore">What is Numstore?</a></li>
<ul class="list-disc ml-6">
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-context">Context</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-historical-precedent-machine-learning">Historical Precedent: Machine Learning</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-historical-precedent-us-intelligence-community">Historical Precedent: US Intelligence Community</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-other-scientific-and-engineering-formats">Other Scientific and Engineering Formats</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-numstores-positioning">Numstore&#x27;s Positioning</a></li>
</ul>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-usecases">Usecases</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-comparison-with-other-databases">Comparison with other Databases</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-metrics-and-numbers">Metrics and Numbers</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-what-can-numstore-not-do">What can Numstore not do?</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-features-cheat-sheet">Features Cheat sheet</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-features-overview">Features Overview</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-getting-started">Getting Started</a></li>
<ul class="list-disc ml-6">
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-linux">Linux</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-windows">Windows</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-mac">Mac</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-main-concepts">Main Concepts</a></li>
</ul>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-vocabulary">Vocabulary</a></li>
<ul class="list-disc ml-6">
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-variable">Variable</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-type">Type</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-array">Array</a></li>
</ul>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-types">Types</a></li>
<ul class="list-disc ml-6">
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-primitive">Primitive</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-struct">Struct</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-union">Union</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-enum">Enum</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-array">Array</a></li>
</ul>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-variable-operations">Variable Operations</a></li>
<ul class="list-disc ml-6">
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-summary">Summary</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-create">Create</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-delete">Delete</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-insert">Insert</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-remove">Remove</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-append">Append</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-take">Take</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-update">Update</a></li>
</ul>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-configuration">Configuration</a></li>
<ul class="list-disc ml-6">
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-variable-level">Variable Level</a></li>
<ul class="list-disc ml-6">
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-windowed">Windowed</a></li>
</ul>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-system-level">System Level</a></li>
<ul class="list-disc ml-6">
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-number-of-threads">Number of Threads</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-page-size">Page Size</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-memory-limits">Memory Limits</a></li>
<ul class="list-disc ml-6">
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-buffer-pool">Buffer Pool</a></li>
</ul>
</ul>
</ul>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-application-programming-interfaces">Application Programming Interfaces</a></li>
<ul class="list-disc ml-6">
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-numstore-c-library">Numstore C Library</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-command-line-interface-cli">Command Line Interface (CLI)</a></li>
<li class="mb-1"><a class="text-blue-600 hover:underline" href="#rawdocs-tcp">TCP</a></li>
</ul>
</ul>
</ul>

<!-- From: Numstore -->
<h1 id="rawdocs-numstore">Numstore</h1>
<NumstoreSection />
<br>

<!-- From: Numstore/What is Numstore? -->
<h2 id="rawdocs-what-is-numstore">What is Numstore?</h2>
<NumstoreWhatIsNumstoreSection />
<br>

<!-- From: Numstore/What is Numstore?/Context -->
<h3 id="rawdocs-context">Context</h3>
<NumstoreWhatIsNumstoreContextSection />
<br>

<!-- From: Numstore/What is Numstore?/Historical Precedent: Machine Learning -->
<h3 id="rawdocs-historical-precedent-machine-learning">Historical Precedent: Machine Learning</h3>
<NumstoreWhatIsNumstoreHistoricalPrecedentMachineLearningSection />
<br>

<!-- From: Numstore/What is Numstore?/Historical Precedent: US Intelligence Community -->
<h3 id="rawdocs-historical-precedent-us-intelligence-community">Historical Precedent: US Intelligence Community</h3>
<NumstoreWhatIsNumstoreHistoricalPrecedentUSIntelligenceCommunitySection />
<br>

<!-- From: Numstore/What is Numstore?/Other Scientific and Engineering Formats -->
<h3 id="rawdocs-other-scientific-and-engineering-formats">Other Scientific and Engineering Formats</h3>
<NumstoreWhatIsNumstoreOtherScientificAndEngineeringFormatsSection />
<br>

<!-- From: Numstore/What is Numstore?/Numstore's Positioning -->
<h3 id="rawdocs-numstores-positioning">Numstore's Positioning</h3>
<NumstoreWhatIsNumstoreNumstoreSPositioningSection />
<br>

<!-- From: Numstore/Usecases -->
<h2 id="rawdocs-usecases">Usecases</h2>
<NumstoreUsecasesSection />
<br>

<!-- From: Numstore/Comparison with other Databases -->
<h2 id="rawdocs-comparison-with-other-databases">Comparison with other Databases</h2>
<NumstoreComparisonWithOtherDatabasesSection />
<br>

<!-- From: Numstore/Metrics and Numbers -->
<h2 id="rawdocs-metrics-and-numbers">Metrics and Numbers</h2>
<NumstoreMetricsAndNumbersSection />
<br>

<!-- From: Numstore/What can Numstore not do? -->
<h2 id="rawdocs-what-can-numstore-not-do">What can Numstore not do?</h2>
<NumstoreWhatCanNumstoreNotDoSection />
<br>

<!-- From: Numstore/Features Cheat sheet -->
<h2 id="rawdocs-features-cheat-sheet">Features Cheat sheet</h2>
<NumstoreFeaturesCheatSheetSection />
<br>

<!-- From: Numstore/Features Overview -->
<h2 id="rawdocs-features-overview">Features Overview</h2>
<NumstoreFeaturesOverviewSection />
<br>

<!-- From: Numstore/Getting Started -->
<h2 id="rawdocs-getting-started">Getting Started</h2>
<NumstoreGettingStartedSection />
<br>

<!-- From: Numstore/Getting Started/Linux -->
<h3 id="rawdocs-linux">Linux</h3>
<NumstoreGettingStartedLinuxSection />
<br>

<!-- From: Numstore/Getting Started/Windows -->
<h3 id="rawdocs-windows">Windows</h3>
<NumstoreGettingStartedWindowsSection />
<br>

<!-- From: Numstore/Getting Started/Mac -->
<h3 id="rawdocs-mac">Mac</h3>
<NumstoreGettingStartedMacSection />
<br>

<!-- From: Numstore/Getting Started/Main Concepts -->
<h3 id="rawdocs-main-concepts">Main Concepts</h3>
<NumstoreGettingStartedMainConceptsSection />
<br>

<!-- From: Numstore/Vocabulary -->
<h2 id="rawdocs-vocabulary">Vocabulary</h2>
<NumstoreVocabularySection />
<br>

<!-- From: Numstore/Vocabulary/Variable -->
<h3 id="rawdocs-variable">Variable</h3>
<NumstoreVocabularyVariableSection />
<br>

<!-- From: Numstore/Vocabulary/Type -->
<h3 id="rawdocs-type">Type</h3>
<NumstoreVocabularyTypeSection />
<br>

<!-- From: Numstore/Vocabulary/Array -->
<h3 id="rawdocs-array">Array</h3>
<NumstoreVocabularyArraySection />
<br>

<!-- From: Numstore/Types -->
<h2 id="rawdocs-types">Types</h2>
<NumstoreTypesSection />
<br>

<!-- From: Numstore/Types/Primitive -->
<h3 id="rawdocs-primitive">Primitive</h3>
<NumstoreTypesPrimitiveSection />
<br>

<!-- From: Numstore/Types/Struct -->
<h3 id="rawdocs-struct">Struct</h3>
<NumstoreTypesStructSection />
<br>

<!-- From: Numstore/Types/Union -->
<h3 id="rawdocs-union">Union</h3>
<NumstoreTypesUnionSection />
<br>

<!-- From: Numstore/Types/Enum -->
<h3 id="rawdocs-enum">Enum</h3>
<NumstoreTypesEnumSection />
<br>

<!-- From: Numstore/Types/Array -->
<h3 id="rawdocs-array">Array</h3>
<NumstoreTypesArraySection />
<br>

<!-- From: Numstore/Variable Operations -->
<h2 id="rawdocs-variable-operations">Variable Operations</h2>
<NumstoreVariableOperationsSection />
<br>

<!-- From: Numstore/Variable Operations/Summary -->
<h3 id="rawdocs-summary">Summary</h3>
<NumstoreVariableOperationsSummarySection />
<br>

<!-- From: Numstore/Variable Operations/Create -->
<h3 id="rawdocs-create">Create</h3>
<NumstoreVariableOperationsCreateSection />
<br>

<!-- From: Numstore/Variable Operations/Delete -->
<h3 id="rawdocs-delete">Delete</h3>
<NumstoreVariableOperationsDeleteSection />
<br>

<!-- From: Numstore/Variable Operations/Insert -->
<h3 id="rawdocs-insert">Insert</h3>
<NumstoreVariableOperationsInsertSection />
<br>

<!-- From: Numstore/Variable Operations/Remove -->
<h3 id="rawdocs-remove">Remove</h3>
<NumstoreVariableOperationsRemoveSection />
<br>

<!-- From: Numstore/Variable Operations/Append -->
<h3 id="rawdocs-append">Append</h3>
<NumstoreVariableOperationsAppendSection />
<br>

<!-- From: Numstore/Variable Operations/Take -->
<h3 id="rawdocs-take">Take</h3>
<NumstoreVariableOperationsTakeSection />
<br>

<!-- From: Numstore/Variable Operations/Update -->
<h3 id="rawdocs-update">Update</h3>
<NumstoreVariableOperationsUpdateSection />
<br>

<!-- From: Numstore/Configuration -->
<h2 id="rawdocs-configuration">Configuration</h2>
<NumstoreConfigurationSection />
<br>

<!-- From: Numstore/Configuration/Variable Level -->
<h3 id="rawdocs-variable-level">Variable Level</h3>
<NumstoreConfigurationVariableLevelSection />
<br>

<!-- From: Numstore/Configuration/Variable Level/Windowed -->
<h4 id="rawdocs-windowed">Windowed</h4>
<NumstoreConfigurationVariableLevelWindowedSection />
<br>

<!-- From: Numstore/Configuration/System Level -->
<h3 id="rawdocs-system-level">System Level</h3>
<NumstoreConfigurationSystemLevelSection />
<br>

<!-- From: Numstore/Configuration/System Level/Number of Threads -->
<h4 id="rawdocs-number-of-threads">Number of Threads</h4>
<NumstoreConfigurationSystemLevelNumberOfThreadsSection />
<br>

<!-- From: Numstore/Configuration/System Level/Page Size -->
<h4 id="rawdocs-page-size">Page Size</h4>
<NumstoreConfigurationSystemLevelPageSizeSection />
<br>

<!-- From: Numstore/Configuration/System Level/Memory Limits -->
<h4 id="rawdocs-memory-limits">Memory Limits</h4>
<NumstoreConfigurationSystemLevelMemoryLimitsSection />
<br>

<!-- From: Numstore/Configuration/System Level/Memory Limits/Buffer Pool -->
<h5 id="rawdocs-buffer-pool">Buffer Pool</h5>
<NumstoreConfigurationSystemLevelMemoryLimitsBufferPoolSection />
<br>

<!-- From: Numstore/Application Programming Interfaces -->
<h2 id="rawdocs-application-programming-interfaces">Application Programming Interfaces</h2>
<NumstoreApplicationProgrammingInterfacesSection />
<br>

<!-- From: Numstore/Application Programming Interfaces/Numstore C Library -->
<h3 id="rawdocs-numstore-c-library">Numstore C Library</h3>
<NumstoreApplicationProgrammingInterfacesNumstoreCLibrarySection />
<br>

<!-- From: Numstore/Application Programming Interfaces/Command Line Interface (CLI) -->
<h3 id="rawdocs-command-line-interface-cli">Command Line Interface (CLI)</h3>
<NumstoreApplicationProgrammingInterfacesCommandLineInterfaceCLISection />
<br>

<!-- From: Numstore/Application Programming Interfaces/TCP -->
<h3 id="rawdocs-tcp">TCP</h3>
<NumstoreApplicationProgrammingInterfacesTCPSection />
<br>

  </div>
</template>

<style scoped>
@reference "tailwindcss";
h1 {
  @apply text-4xl font-bold leading-tight;
}

h2 {
  @apply text-3xl font-bold leading-tight;
}

h3 {
  @apply text-2xl font-bold leading-tight;
}

h4 {
  @apply text-xl  font-bold leading-tight;
}
</style>
