name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Linux dependencies
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang-tidy

      # macOS dependencies
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install make llvm
          echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH  # Ensure clang-tidy is in PATH

      - name: Verify clang-tidy is available
        run: clang-tidy --version

      - name: Build the project
        run: make

      - name: Run tests
        run: ./test
        continue-on-error: false

      - name: Lint
        run: make lint
        continue-on-error: false

